### ISSUE TITLE
Save multiple pdf to folder

### ISSUE THREAD

**Issue by HawiCaesar** [niklasravnsborg/laravel-pdf#1]
This works great! Thanks for the tutorial!

However is there a way to save multiple pdf's to a folder instead of opening them via browser?

like say I click a button and it generates many pdf's in a folder I specifiy...Hope this makes sense?

**Comment by niklasravnsborg** [comment]
@HawiCaesar Hey! You can use the [$pdf->save($filename)](https://github.com/niklasravnsborg/laravel-pdf/blob/master/src/LaravelPdf/PdfWrapper.php#L83) method. Maybe loop over an array and output many PDFs on the way.
