### ISSUE TITLE
Creating multiple PDF documents, problem with single instance of mpdf object

### ISSUE THREAD

**Issue by lkreher** [niklasravnsborg/laravel-pdf#10]
This project uses the same instance of the mpdf object every time the facade is called. This is a problem when the goal is to create multiple files. 
[This fork](https://github.com/hugo8xx/laravel-pdf) fixed the problem with a rather nasty hack, by creating a new instance of the mpdf object every time the save() facade is called. Is there any way to add this feature to your project?

**Comment by niklasravnsborg** [comment]
I decided to use the same mpdf instance to preserve memory. But why is this a problem when you try to generate multiple files?

Open for discussion and your improvement here! :)

**Comment by cosmo-tapptic** [comment]
Hi, there
I find the problem even in such a simple example:
        $pdf = \niklasravnsborg\LaravelPdf\Facades\Pdf::loadView('asimpletemplate');
        $pdf->save('out.pdf');
        $pdf->save('out2.pdf');
so the second file is bigger and broken (only some pdf browsers open it)
There are few lines added to the second after %%EOF

**Comment by lkreher** [comment]
@cosmo-tapptic already pointed out part of the problem, the bigger issue for me is trying to save different views to different files:
`\niklasravnsborg\LaravelPdf\Facades\Pdf::loadView('template1')->save('out1.pdf');
\niklasravnsborg\LaravelPdf\Facades\Pdf::loadView('template2')->save('out2.pdf');`
In this case the 2nd file still contains the content from the first template plus an empty 2nd page. 

My not very creative solution is to create a new instance of the mpdf object every time save() is called. 
I tried doing
`$mpdf = clone $this->mpdf;`
and use that instance to generate the output, but for some reason unknown to me this always produced corrupted files.

**Comment by niklasravnsborg** [comment]
@lkreher @cosmo-tapptic Now have time to look into this again! I now see your problem and I'll try to initiate a new mPDF internally when the facade gets constructed.

**Comment by niklasravnsborg** [comment]
@lkreher @cosmo-tapptic I added multiple internal PDF instances in 8b58e05871b36086e06af6671634874e8b1d17bc. Please try if this works for you! ☺️

**Comment by cosmo-tapptic** [comment]
Works (thank you) fine if I make small change one line ;)
src/LaravelPdf/Pdf.php line 23:
define(_MPDF_SYSTEM_TTFONTS_CONFIG, __DIR__ . '/../mpdf_ttfonts_config.php');
into
define('_MPDF_SYSTEM_TTFONTS_CONFIG', __DIR__ . '/../mpdf_ttfonts_config.php');

**Comment by niklasravnsborg** [comment]
@cosmo-tapptic Thats weird... What PHP version are you using? What error do you get with the package code?

**Comment by cosmo-tapptic** [comment]
Use of undefined constant _MPDF_SYSTEM_TTFONTS_CONFIG.
Defining constant without " gives you a notice and I report like E_ALL

**Comment by niklasravnsborg** [comment]
@cosmo-tapptic Well on my system and on our production software it works without any problems...

**Comment by niklasravnsborg** [comment]
@cosmo-tapptic I added the `'` in ef12fa045388ba7b7ffddd256f26f06690789232 ☺️ let me know if this works for you

**Comment by cosmo-tapptic** [comment]
Yeap, works fine!
Sorry for answering so late!
And thank you, @niklasravnsborg :)

**Comment by niklasravnsborg** [comment]
@cosmo-tapptic Awesome!
