### ISSUE TITLE
Undefined Index: diid

### ISSUE THREAD

**Issue by darkside-e** [niklasravnsborg/laravel-pdf#101]
![screenshot00068](https://user-images.githubusercontent.com/34475779/42515399-5ba70dd6-8464-11e8-8a21-5850d372750e.png)

Hello,
So I have this question table in my database with both english and arabic version of the question. The table is in utf8mb4 charset and both the english and the arabic version in it are in utf8mb4 charset too. When i print them inside the html page they are printed correctly, but when I generate the pdf from the html file I get this error...any idea why?

**Comment by erfansahaf** [comment]
Hi there,

I had the same problem with putting `Gm` music chord in PDF. When I changed it, everything worked fine.
So check your text that you are trying to produce, in this case, you have to debug and find out what is that word or text that causes this issue.
