### ISSUE TITLE
Please update mpdf dependency

### ISSUE THREAD

**Issue by dheroefic** [niklasravnsborg/laravel-pdf#103]
Hello,

Thanks for this wonderful library, we really love it!
I got an issue installing this with Laravel 5.6 and PHP 7.1

> PHP Fatal error:  Cannot redeclare dd()

It might be related to this issue [PHP Fatal error: Cannot redeclare dd() (Laravel) #410](https://github.com/mpdf/mpdf/issues/410) and this [Using mpdf/mpdf (v7.0.0-beta1) with Laravel 5.2 - redeclaring method dd()](https://github.com/mpdf/mpdf/issues/445)

Below is the screenshot
![image](https://user-images.githubusercontent.com/25289400/43558569-5e01968c-9634-11e8-8668-e5bd8e0b9f0f.png)

Thanks,

Fadel.

**Comment by niklasravnsborg** [comment]
@dheroefic Hello! Thanks for the report. Can you try this on Linux also to exclude Windows from being the problem?

**Comment by dheroefic** [comment]
@niklasravnsborg sure, let me test it using Windows Subsystem for Linux and actual Linux Server.

**Comment by dheroefic** [comment]
@niklasravnsborg Still get an error with PHP 7.1 and Laravel 5.6

Below is the screenshot
![image](https://user-images.githubusercontent.com/25289400/43623117-bd13dbe6-9709-11e8-9427-d4c1c4786866.png)

I've resolved it by installing mpdf (7.1.1) first and installing this library afterward.

**Comment by EvilLooney** [comment]
Hi,

I just want to say this package was working until I tried a composer update; it downgraded mpdf:
`Downgrading mpdf/mpdf (v7.1.1 => v7.0.0-beta1): Loading from cache`
and then got the error mentioned above.

I had to revert my composer lock file to fix my problem.

**Comment by dheroefic** [comment]
I don't know what's going on. But today, when I was starting the project from scratch and installing this library again this is what happened
![image](https://user-images.githubusercontent.com/25289400/43987631-d52a57ec-9d4d-11e8-8651-b8f8b4c4b419.png)

Maybe it's composer glitch after all, or maybe because mpdf update its package to v7.1.4? So now I'm closing this issue.
