### ISSUE TITLE
Pagination on Cover Image

### ISSUE THREAD

**Issue by litus92** [niklasravnsborg/laravel-pdf#105]
I'm loading a blade with a cover image and then the rest of the content. The cover image fills the full first page. I'm paginating all the pages using the < htmlpagefooter > tag and inside I use {PAGENO} to paginate them. 

The problem is that I want to paginate all of them but not the cover page, I mean not the first one. 

How could I do that? 

Thanks!

**Comment by niklasravnsborg** [comment]
@litus92 I don't know exactly what you mean. Hope you figured it out. Will close this now.
