### ISSUE TITLE
CSS link not working

### ISSUE THREAD

**Issue by abdulazizalrawahi** [niklasravnsborg/laravel-pdf#107]
I linked bootstrap in the header, but it is not reflected when pdf is generated
`<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">`
only inline css is working

**Comment by niklasravnsborg** [comment]
Yep, that won't work with mdpf. You can't use any external CSS.

This would be an issue of https://github.com/mpdf/mpdf

**Comment by abdulazizalrawahi** [comment]
Even if I write css in style tag it wont work.

**Comment by erfansahaf** [comment]
@abdulazizalrawahi Keep in mind that mPDF just supports basic CSS styles, not complicated ones like Bootstrap or other frameworks.
