### ISSUE TITLE
ErrorException in cssmgr.php line 1302

### ISSUE THREAD

**Issue by ismlcam** [niklasravnsborg/laravel-pdf#11]
Hey, 

Please help :(

I just installed this package. Have followed your instructions point to point, but is give me an error message when I try to display a pdf.

Error details:
ErrorException in cssmgr.php line 1302.
Illegal string offset 'ID'
in cssmgr.php line 1302
at HandleExceptions->handleError('2', 'Illegal string offset 'ID'', '.../vendor/niklasravnsborg/mpdf/classes/cssmgr.php', '1302', array('inherit' => 'BLOCK', 'tag' => 'BODY', 'attr' => '', 'p' => array(), 'zp' => array(), 'classes' => array())) in cssmgr.php line 1302
at cssmgr->MergeCSS('BLOCK', 'BODY', '') in mpdf.php line 15961

**Comment by niklasravnsborg** [comment]
To be honest I don't know where this error is coming from. Can you send me your code snippet where you are initiating and saving the PDF?

**Comment by niklasravnsborg** [comment]
@ismlcam Could you fix this?

**Comment by JoeyHoutenbos** [comment]
@niklasravnsborg same problem here. Seems the upgrade to PHP7.1 changed something..

**Comment by bigstepdenmark** [comment]
Hey, sorry for the late answer.

I fix the problem, but think is not the best way to solved.

vendor/niklasravnsborg/mpdf/classes/cssmgr and comment following lines:

1. go to function MergeCSS($inherit, $tag, $attr)
and comment this lines 

`if (!isset($attr['ID'])) {
			$attr['ID'] = '';
		}
		// mPDF 6
		$shortlang = '';
		if (!isset($attr['LANG'])) {
			$attr['LANG'] = '';
		} else {
			$attr['LANG'] = strtolower($attr['LANG']);
			if (strlen($attr['LANG']) == 5) {
				$shortlang = substr($attr['LANG'], 0, 2);
			}
		}`

And this line

`$this->_mergeFullCSS($this->cascadeCSS, $this->mpdf->blk[$this->mpdf->blklvl]['cascadeCSS'], $tag, $classes, $attr['ID'], $attr['LANG']);`

its solve my problem. I hope you can find a better solution.

**Comment by Sheby** [comment]
@niklasravnsborg this was fixed in master mpdf/classes/cssmgr.php, could you update your fork of the mpdf? or replace your composer dependency from niklasravnsborg/mpdf to mpdf/mpdf

**Comment by niklasravnsborg** [comment]
@Sheby Yes I will do! Thanks :)

**Comment by niklasravnsborg** [comment]
@Sheby https://github.com/niklasravnsborg/laravel-pdf/commit/0c6e0c3094973e929ae0abb6f095e9b20cfaa7b0 switched to use original mpdf again. Back in April I had to create an own fork because the mpdf repo was in beta and that caused issues with composers minimum-stability.

Now everything should work fine :)

**Comment by Sheby** [comment]
one more thing in your PdfServiceProvider.php change

```include base_path('vendor/niklasravnsborg/mpdf/mpdf.php');```
to

```include base_path('vendor/mpdf/mpdf/mpdf.php');```

**Comment by niklasravnsborg** [comment]
@Sheby Yep! Should be testing before commiting 😆

**Comment by niklasravnsborg** [comment]
@Sheby https://github.com/niklasravnsborg/laravel-pdf/commit/c38273ea3a1f7f31b75d3f65315aca4406d00ce9 did it
