### ISSUE TITLE
stream in new tab

### ISSUE THREAD

**Issue by lucaskaiut** [niklasravnsborg/laravel-pdf#111]
How can I stream the pdf on a new tab? I'm using laravel, when I click the button, it calls the method that generate pdf, but it should redirect for another page

**Comment by zymawy** [comment]
You Could Do it Via Ajax: 

```javascript 
var ids = [];
var type = "";
$('button').click(function() {
       window.open('/api/v1/export/selectedMember?id='+ids + '&type=' + type);
});

**Comment by lucaskaiut** [comment]
ok
I don't know a thing about ajax or anything envolving javascript, but know I know what I'm looking for. Thank you!

**Comment by zymawy** [comment]
Php Can't Work On The Client Side. That Being Side You Can't Open Now Tab From The Server You Need Javascript To Accomplish The Task. Good Luck.

**Comment by niklasravnsborg** [comment]
Thanks guys. Will close this now.
