### ISSUE TITLE
HTML Pagebreak orientation not working

### ISSUE THREAD

**Issue by mattogodoy** [niklasravnsborg/laravel-pdf#122]
Hi!

I know this has been reported before, but in PHP. I also want to add that the landscape option in the HTML pagebreak (https://mpdf.github.io/reference/html-control-tags/pagebreak.html) does not work.

I've tried with `<pagebreak orientation="L" />` and `<pagebreak orientation="landscape" />`, but no luck.

As a temporary fix I've added this to my CSS:
```css
@page landscape {
    size: landscape;
}
```

And this to my HTML: `<pagebreak page-selector="landscape" />`

I hope this can help someone.

**Comment by erfansahaf** [comment]
Please check it on the `mPDF`. If the problem still exists, report it on the original repo issues page, `laravel-pdf` is just a wrapper. And if not, let us know.
Close this for now.
