### ISSUE TITLE
img tag with asset src don't work

### ISSUE THREAD

**Issue by OAmor** [niklasravnsborg/laravel-pdf#123]
i'm trying to set an image in my pdf but it just doesn't work i've tried using the full path but the same problem appear (pdf page will be stuck in loading and nothing appear)
this is my tag `<img src="{{asset('images/currency.jpeg')}}" alt="">`
and in my controller 
`            $pdf=PDF::loadHTML(view('invoice.ar.invoicev1')->with('data',$request));
            return $pdf->stream();
`
i'm using last version of laravel 5.7

**Comment by niklasravnsborg** [comment]
Please don't use the `asset()` helper. The image path should be relative to the PHP runtime / e.g. the Laravel project. As far as I know `asset()` gives you an URL.

**Comment by erfansahaf** [comment]
As the Niklas said, the `assets()` will not work cause it isn't a web page. You could use  `base_path()` instead.
For example, if you want to use an image inside the public folder:
```php
{{ base_path().DIRECTORY_SEPARATOR.'public'.DIRECTORY_SEPARATOR.'image.png' }}
```
