### ISSUE TITLE
Which type to use for attach pdf to Mail, 

### ISSUE THREAD

**Issue by marwan2** [niklasravnsborg/laravel-pdf#125]
I'm trying to use $pdf->output();
To attach the PDF file to email, using the following code: 

`$invoice_record = Invoice::first();
            $invoice_content = Invoice::get_inv_template($invoice_record);

            $pdf_name = 'Invoice'.$invoice_record->invoice_id.'_'.date('Y_m_d').'.pdf';
            $config = [
                'mode' => 'utf-8',
            ];
            $pdf = PDF::loadHTML($invoice_content, $config);

            return $this
                ->subject($this->mail_info['subject'])
                ->markdown('invoices.emails.sales_invoice')
                ->with([
                    'mail_body'=>$this->mail_info['body']
                ])
                ->attachData($pdf->output(), $pdf_name, [
                    'mime' => 'application/pdf',
            ]);`

Nothing happend, even email not sent

**Comment by marwan2** [comment]
OK I handled it.

**Comment by nickclasener** [comment]
```php
$pdf = PDF::loadHtml($this->templateHtml)
            ->output();

return $this->markdown('.emails.pdf')
            ->with('data', $this->data)
            ->attachData($pdf, Str::slug($this->data->name).'.pdf', [
                'mime' => 'application/pdf',
            ]);
```
