### ISSUE TITLE
Emoji not showing in pdf

### ISSUE THREAD

**Issue by umairali** [niklasravnsborg/laravel-pdf#126]
Emoji is not showing correctly in pdf. Emoji showing as box with ? question mark

 
![capture](https://user-images.githubusercontent.com/5318005/52518601-422c5a00-2c66-11e9-9bdb-62189fb35b18.PNG)

origional text with emoji

![capturedf](https://user-images.githubusercontent.com/5318005/52518629-bd8e0b80-2c66-11e9-97c6-db18f44f4962.PNG)

**Comment by erfansahaf** [comment]
Of course, it can not render emojis. You should use emojis' image with `img` HTML tag in your view template.

**Comment by niklasravnsborg** [comment]
@umairali This is also related to mPDF. This repo is just a wrapper for Laravel. In order to render emojis mPDF would have to implement a correct UTF-8 parsing for the emoji spec, I think.

**Comment by umairali** [comment]
I fixed this issue with seguiemj custom font.
