### ISSUE TITLE
Custom Pdf Configuration Style Not Working

### ISSUE THREAD

**Issue by umairali** [niklasravnsborg/laravel-pdf#13]
I am changing mpdf code codeigniter to laravel.

## **Codeigniter** 
```
$pdf = $this->pdf->load();
$pdf->mPDF('utf-8',    // mode - default ''
                'A4',  // format - A4, for example, default ''
                0,     // font size - default 0
                '',    // default font family
                0,    // margin_left
                0,    // margin right
                0,    // margin top
                0,    // margin bottom
                0,     // margin header
                0,     // margin footer
                'L');  // L - landscape, P - portrait
```

but in laravel I am using below code but it's not working. 

## **Laravel**
```
$pdf = PDF::loadView('pdf.invoice', $data);
 $pdf->mPDF('utf-8',    // mode - default ''
                'A4',  // format - A4, for example, default ''
                0,     // font size - default 0
                '',    // default font family
                0,    // margin_left
                0,    // margin right
                0,    // margin top
                0,    // margin bottom
                0,     // margin header
                0,     // margin footer
                'L');  // L - landscape, P - portrait
 $pdf->save($pdfFilePath);
```

**Comment by niklasravnsborg** [comment]
@umairali What kind of error do you get?

**Comment by umairali** [comment]
FatalErrorException in orderpdf.php
Call to a member function mPDF() on string

**Comment by andreich1980** [comment]
@umairali for laravel 5.3 use this code
```
return PDF::loadView('your-view-here', compact('any-variable-to-pass-in-the-view'))
                 ->download('your-pdf-name.pdf');
```
and you will download the pdf.

If you want to just view it in your browser, use `stream` instead of `download`

**Comment by niklasravnsborg** [comment]
@umairali Did this work for you?

**Comment by umairali** [comment]
I am already using the same code for passing data to view.

`
$data = [
      'name' => $name,
      'email' => $email,
      'mobile' => $mobile,
      'address' => $address
];

PDF::loadView('pdf.invoice', $data)->save($pdfFilePath);
` 

But my question is related to whole page style like pdf.php config file. Below code is for all pdf in the project but how can I pass this for separate pdf. 

`
<?php

return [
    'mode'                  => 'utf-8',
    'format'                => 'A4',
    'default_font_size'     => '',
    'default_font'          => 'chevin',
    'margin_left'           => 0,
    'margin_right'          => 0,
    'margin_top'            => 0,
    'margin_bottom'         => 0,
    'margin_header'         => 0,
    'margin_footer'         => 0,
    'orientation'           => 'P',
    'title'                 => '',
    'author'                => '',
    'watermark'             => '',
    'show_watermark'        => false,
    'watermark_font'        => 'chevin',
    'display_mode'          => 'fullpage',
    'watermark_text_alpha'  => 0.1,
    'custom_font_path' => base_path('/resources/fonts/'), // don't forget the trailing slash!
    'custom_font_data' => [
        'chevin' => [
            'R'  => 'ChevinLight.ttf',    // regular font
            'B'  => 'ChevinBold.ttf',     // optional: bold font
            'I'  => 'ChevinLight.ttf',    // optional: italic font
            'BI' => 'ChevinBold.ttf'      // optional: bold-italic font
        ],
        'dinnextltarabic' => [
            'R'  => 'DINNextLTArabic-Light.ttf',    // regular font
            'B'  => 'DINNextLTArabic.ttf',          // optional: bold font
            'I'  => 'DINNextLTArabic-Light.ttf',    // optional: italic font
            'BI' => 'DINNextLTArabic.ttf'           // optional: bold-italic font
        ]
    ]
];
`

**Comment by niklasravnsborg** [comment]
@umairali It seems like you are not using this package, right? Are you using this package or mPDF?
Would like to help...

See https://github.com/mpdf/mpdf and https://github.com/niklasravnsborg/laravel-pdf

**Comment by umairali** [comment]
I am using same package

https://github.com/niklasravnsborg/laravel-pdf

**Comment by niklasravnsborg** [comment]
@umairali So your code you posted earlier it is obvious that it doesn't work.

```php
$pdf = PDF::loadView('pdf.invoice', $data);
 $pdf->mPDF('utf-8',    // mode - default ''
                'A4',  // format - A4, for example, default ''
                0,     // font size - default 0
                '',    // default font family
                0,    // margin_left
                0,    // margin right
                0,    // margin top
                0,    // margin bottom
                0,     // margin header
                0,     // margin footer
                'L');  // L - landscape, P - portrait
 $pdf->save($pdfFilePath);
```

`mPDF` is not a method you can use in this context. Use the pdf.php config file instead. I saw you figured that out. 😌 

The other code you posted works for me. If I understood you correctly you want to be able to change configuration between different PDFs, right?

**Comment by niklasravnsborg** [comment]
@umairali  I implemented custom config in 2dc7281c1b6f520a018e9868c2ec9d815748ad5e. Does this work for you?

**Comment by umairali** [comment]
Can you please give me a little example how I use this in my code.

**Comment by niklasravnsborg** [comment]
@umairali Sure! You use the `loadView()` method. The custom config is the fourth parameter. 
For example set a custom left margin for this PDF:

```php
PDF::loadView('pdf.invoice', $data, [], [
  'margin_left' => 0
])->save($pdfFilePath);
```

You can pass any config here. Let me know if this helps.

**Comment by umairali** [comment]
thanks
