### ISSUE TITLE
Rendering charts on PDF

### ISSUE THREAD

**Issue by aparedesBB** [niklasravnsborg/laravel-pdf#130]
Is it possible to render charts with this library? I am using lavacharts and I already convert them to png. I've tried with several different libraries but I'm still not able to make it work. So, before I start, is it possible to render charts with laravel-pdf?

**Comment by niklasravnsborg** [comment]
Hey Laravel PDF is just a wrapper for https://mpdf.github.io/. Everything that works with mPDF works with Laravel PDF. The feature set is a pretty limited CSS spec. But if you have a PNG you should be able to render it.
