### ISSUE TITLE
How I can create table of contents automatically?

### ISSUE THREAD

**Issue by matiullah-netlinks** [niklasravnsborg/laravel-pdf#131]

**Comment by andreich1980** [comment]
I don't think it's a job for _pdf-generator_. You can do it yourself before sending data to the generator.

**Comment by matiullah-netlinks** [comment]
@andreich1980 Then, how should I know which content is at which page?

**Comment by niklasravnsborg** [comment]
As @andreich1980 said this is a job you have to handle on your own. I don't think there is a way to find out which content is on what page. Maybe you can find something regarding that on the mPDF docs?

**Comment by matiullah-netlinks** [comment]
@niklasravnsborg mpdf has support for this.
https://mpdf.github.io/what-else-can-i-do/table-of-contents.html

**Comment by matiullah-netlinks** [comment]
I gonna close this issue
