### ISSUE TITLE
Warning - You cannot set this font (/home/public_html/public/fonts/GE_Thameen_Light.ttf) to use OTL, as it does not include OTL tables (or at least, not a GDEF table)

### ISSUE THREAD

**Issue by ahmadelsaeed** [niklasravnsborg/laravel-pdf#132]
I Use Custome font and get this error

Warning - You cannot set this font (/home/public_html/public/fonts/GE_Thameen_Light.ttf) to use OTL, as it does not include OTL tables (or at least, not a GDEF table)

My Code

```
return [
	'default_font'         => 'sans-serif',
	'orientation'          => 'P',
	'display_mode'         => 'fullpage',
	'custom_font_dir'      => '/fonts/GESSTwoLight',
	'custom_font_data' 	   => [
		'gesstwoLightlight' => [
			'R'  => 'GESSTwoLight-Light.ttf',   
			'useOTL' => 0xFF,  
			'useKashida' => 75,
		]
	]
];
```
Thanks in advance

**Comment by erfansahaf** [comment]
Your font is not supported because it is not standard. Try another font and make sure that your font has OTL tables.
