### ISSUE TITLE
Upgrade to mpdf 8

### ISSUE THREAD

**Issue by yurykozyrev** [niklasravnsborg/laravel-pdf#133]
Mpdf 8 was released in March, could we consider upgrade ?

**Comment by niklasravnsborg** [comment]
Sure! @daveismyname do you have some time for this?

**Comment by fdyckhoff** [comment]
I would appreciate if you do the upgrade because it should fix a bug with broken links when merging multiple pdf files. :)  see https://github.com/mpdf/mpdf/issues/900

**Comment by niklasravnsborg** [comment]
We upgraded mpdf in version 4.0.0 of this package.
