### ISSUE TITLE
Erorr while updating 

### ISSUE THREAD

**Issue by erfantkerfan** [niklasravnsborg/laravel-pdf#134]
setasign/fpdi suggests installing setasign/fpdf (FPDI will extend this class but as it is also possible to use "tecnickcom/tcpdf" as an alternative there's no fixed dependency configured.)
setasign/fpdi suggests installing setasign/fpdi-fpdf (Use this package to automatically evaluate dependencies to FPDF.)
setasign/fpdi suggests installing setasign/fpdi-tcpdf (Use this package to automatically evaluate dependencies to TCPDF.)

**Comment by erfansahaf** [comment]
You can move on because they are warnings, not errors!
