### ISSUE TITLE
laravel 5.8 can not found this libs

### ISSUE THREAD

**Issue by heidaryBhnam** [niklasravnsborg/laravel-pdf#135]
**Describe the bug**
the service and alias not work true

**To Reproduce**
in the controller i have below code:

> use niklasravnsborg\LaravelPdf\Pdf as PDF;
class ReportsController extends Controller {
    public function report() {
        $data = ['foo', 'bar'];
        $pdf = PDF::loadView('myPDF', $data);
        return $pdf->stream('document.pdf');
    }
}

but error in load is `Call to undefined method niklasravnsborg\LaravelPdf\Pdf::loadView()`
so i try `use PDF` and all files in `niklasravnsborg\LaravelPdf\` but not working for me.
all install levels are do it currectly. `composer install` OK and `config/app.php` setting are do it. then `php artisan vendor:publish` worked true.
where is problem.

**Environment (please complete the following information):**
 - Laravel version = 5.8
 - PHP version = 7.3
 - Installed laravel-pdf version = 3.1

**Comment by msadeghyan1996** [comment]
for me in Laravel 5.8 when i get PDF::loadView page stay on loading mode and write wating for 127.0.0.1 and not finish loading!!

**Comment by udemethegrtman** [comment]
@msadeghyan1996  same thing for me in laravel 5.8, loading forever...

**Comment by fkranenburg** [comment]
Laravel 5.8 does not work, it is loading the PDF and does not finish. Could this be fixed?

**Comment by alirezakatiraie** [comment]
Same problem here, tryin to use with Laravel 7.5.2 :
`use niklasravnsborg\LaravelPdf\Pdf as PDF;`
`    public function get_new_order(Order $order)
    {
        $pdf = PDF::loadView('pdf_templates.receipt', ['order'=>$order]);
        return $pdf->stream('invoice.pdf');
    }`
and i get 500 error.
any solution ?

**Comment by alirezakatiraie** [comment]
Same problem here, tryin to use with Laravel 7.5.2 :

> use niklasravnsborg\LaravelPdf\Pdf as PDF;

> public function get_new_order(Order $order)
    {
        $pdf = PDF::loadView('pdf_templates.receipt', ['order'=>$order]);
        return $pdf->stream('invoice.pdf');
    }

and i get : 

> Error
> Call to undefined method niklasravnsborg\LaravelPdf\Pdf::loadView()

any solution ?

**Comment by erfansahaf** [comment]
If it takes to long to generate the response, it may be caused by your template.
Please provide both your PHP codes and PDF template.

**Comment by niklasravnsborg** [comment]
@heidaryBhnam Your import looks wrong to me. Please use the library as stated in the documentation. You have to declare a Laravel alias via the configuration.
