### ISSUE TITLE
The process has been signaled with signal "4".

### ISSUE THREAD

**Issue by sujitkv92** [niklasravnsborg/laravel-pdf#136]
Symfony \ Component \ Process \ Exception \ ProcessSignaledException
The process has been signaled with signal "4".

getting in $pdf->download() and $pdf->save() function

**Comment by erfansahaf** [comment]
Hey there,
As I found, are you sure that you are not running out of memory? I think it caused because of low memory space.

**Comment by erfansahaf** [comment]
Closed because of no response.
