### ISSUE TITLE
not working in Lumen

### ISSUE THREAD

**Issue by kiasaty** [niklasravnsborg/laravel-pdf#138]
The package doesn't work in Lumen and has errors.
I changed Config::get() to config() and the same thing about app()->basePath and it worked.

another issue is, when I upload a new font and configure it in the config file, and add as css in the blade, the font doesn't take effect.

**Comment by erfansahaf** [comment]
Could you please provide your stack details? (PHP, Lumen and Laravel-PDF versions)

**Comment by erfansahaf** [comment]
Closing because of no response.
