### ISSUE TITLE
stay on loading mode in Laravel 5.8

### ISSUE THREAD

**Issue by msadeghyan1996** [niklasravnsborg/laravel-pdf#139]
Hi.
I user laravel 5.8 and install this package for generate pdf file.
i use jquery chart in view and i need generate pdf file with view but when i get 
``` $pdf = PDF::loadView('disc.pdf', ['datas'=>$datas]);```
 method page stay in loading mode and not finish.

**Comment by erfansahaf** [comment]
Hey there,
You can not use jQuery on a PDF view, only basic HTML/CSS commands are available.
The alternative way of doing such a thing is making an image of the rendered chart and embed that image on the pdf view.

**Comment by msadeghyan1996** [comment]
very tanx erfan. so i can't use chart or any js tools in pdf. how i can do it and generate image of chart?

**Comment by msadeghyan1996** [comment]
and erfan why page stay on loading mode and not finish?

**Comment by erfansahaf** [comment]
@msadeghyan1996 You should look for a Javascript library which lets you make an image of your chart, google it and you'll find one.
About staying on loading, I can say that there is something wrong with your view. Probably you have used wrong image address or unsupported tags/scripts. Try again with a fresh view which contains a single HTML heading tag. You should be fine.
