### ISSUE TITLE
Pdf include

### ISSUE THREAD

**Issue by cipribucur** [niklasravnsborg/laravel-pdf#14]
Hi, the include in the PdfServiceProvider is not working anymore, now that you've change to the mpdf/mpdf, he's looking in the wrong directory. Can you update the path there also? thanks.

**Comment by niklasravnsborg** [comment]
Sure! Fixed with https://github.com/niklasravnsborg/laravel-pdf/commit/c38273ea3a1f7f31b75d3f65315aca4406d00ce9 in v1.1.4 ☺️
