### ISSUE TITLE
i need footer template start at page 2

### ISSUE THREAD

**Issue by msadeghyan1996** [niklasravnsborg/laravel-pdf#140]
Hi
I use ```htmlpagefooter``` tag in my project but i need footer start at page2.
i don't need footer and header in page1.

**Comment by nicolasvac** [comment]
Just check for pagenumber and start printing if pagenumber is >= 2

**Comment by niklasravnsborg** [comment]
I will close this issue since this is a support question.

**Comment by msadeghyan1996** [comment]
[https://github.com/niklasravnsborg/laravel-pdf/issues/114](114)
