### ISSUE TITLE
How to use Chinese fonts, such as NotoSans-Regular.ttf

### ISSUE THREAD

**Issue by longyunrui** [niklasravnsborg/laravel-pdf#142]
**Describe the bug**
How to use Chinese fonts, such as NotoSans-Regular.ttf; 
 English fonts can be customized normally

**Comment by erfansahaf** [comment]
Please [read the documentation](https://github.com/niklasravnsborg/laravel-pdf#custom-fonts).

**Comment by longyunrui** [comment]
> Please [read the documentation](https://github.com/niklasravnsborg/laravel-pdf#custom-fonts).

。。。。
