### ISSUE TITLE
CSS not working correctly

### ISSUE THREAD

**Issue by PSPTora** [niklasravnsborg/laravel-pdf#143]
Hello, Thanks for keep supporting this package. This package seems almost perfect for me but There still one problem about CSS.
It is not working with "Display", and "Position" .
I tried using display:none, but it is not working nor display:inline, or display:block.
For postion:absolute or relative, it is not working either.
I would love to know it is working or is it just me.

**Comment by Malkom** [comment]
Hi,

Property  `'defaultCssFile'        => '/public/css/app.css'`  in `config/pdf.php` is not working.

Any idea ?

**Comment by Eliot8** [comment]
try to make the path like public_path('/public/css/app.css')

**Comment by niklasravnsborg** [comment]
Hey! laravel-pdf uses mpdf unser the hood. CSS isn‘t supported in the way as it is by browsers. Please consult the documentation of mpdf.
