### ISSUE TITLE
Specifying Page Size 

### ISSUE THREAD

**Issue by memoishin** [niklasravnsborg/laravel-pdf#151]
I would like to know how can page size be specified in millimeters. 

According to mpdf docs, it is like this:
// Define a default page size/format by array - page will be 190mm wide x 236mm height
`$mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8', 'format' => 'utf-8', [190, 236]]);`

How can this be achieved in laravel-pdf?

**Comment by memoishin** [comment]
Managed to figure it out. 
It has to be specified like this:
```
$pdf = PDF::loadView('pdfs.labelname', $data, [], [
       'format' => [190, 236]
]);
```
Thanks

**Comment by niklasravnsborg** [comment]
Glad that you figured it out :)
