### ISSUE TITLE
Using the development branch of mpdf

### ISSUE THREAD

**Issue by ravenberg** [niklasravnsborg/laravel-pdf#153]
Hi, I was about to check out your library and I noticed during installation that it installs the (less stable) development branch of `mpdf/mpdf`. 

![image](https://user-images.githubusercontent.com/8441153/71250514-2383fe80-2320-11ea-8b58-a8dd88118284.png)

I noticed you are requiring `^7.0` yet it installs the `development` branch. Perhaps it has something to do with them changing the default branch to `development`? Anyhow I thought it would be nice to let you know.

**Comment by niklasravnsborg** [comment]
Hey @ravenberg,

I‘m sure I can close this issue, since we released a new version of this package which includes the newest stable version of mpdf.

**Comment by ravenberg** [comment]
Yeah, thanks!
