### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by lksnmnn** [niklasravnsborg/laravel-pdf#156]
Just an heads up: 

I am not sure if you can simply wrap the GPL licensed mPDF library and make it MIT.

Cheers,
Lukas

**Comment by niklasravnsborg** [comment]
Hey @lksnmnn, thanks for your heads up! I'm not quite sure as well but I didn't extend or modify the mPDF library in any way. No source code from mPDF is contained in this repository. The MIT license should only regard code that I and collaborators of this repository wrote.

Do you still see an issue with that?
