### ISSUE TITLE
Uppercased custom font name doesn't work

### ISSUE THREAD

**Issue by MahdiFakhrabadi** [niklasravnsborg/laravel-pdf#158]
When defining custom fonts, the name of font must be lowercased, otherwise if it contains uppercased name like "Sans-Serif", it wouldn't work.
The point of this issue is to update documentation to mention the font name should be all lowercase letters to make it work.

**Comment by erfansahaf** [comment]
Yes, that's true. The fonts' name should be lowercase. Your PR is welcome!
