### ISSUE TITLE
run time error 

### ISSUE THREAD

**Issue by maryamMOMENII** [niklasravnsborg/laravel-pdf#159]
hi,
i need set image for back ground in pdf file .
when i using image in view , i get this error .

Maximum execution time of 60 seconds exceeded

i set more than time 60 and not resolved.

**Comment by erfansahaf** [comment]
I guess you used the image URL instead of its path.
Take a look at this: https://github.com/niklasravnsborg/laravel-pdf/issues/94#issuecomment-400650754

**Comment by erfansahaf** [comment]
I guess you used the image URL instead of its path.
Take a look at this: https://github.com/niklasravnsborg/laravel-pdf/issues/94#issuecomment-400650754
