### ISSUE TITLE
I can't turn `showWatermarkImage` off

### ISSUE THREAD

**Issue by vzool** [niklasravnsborg/laravel-pdf#16]
Hi,
I'm facing a problem that I want to show a water mark in first page only and not all pages.
So, I think we need to make `$this->mpdf->showWatermarkImage` `false` and sometimes `$this->mpdf->showWatermarkText` `false` also.
I suggest it's better to make a new function called `obj()` which referenced to `$mpdf`.

Thanks in Advance

**Comment by vzool** [comment]
In fact, **mPDF** has many options needs to be changed many time depends on the layout target.

So, Here is the snippet:

```
public function obj(){
	return $this->mpdf;
}
```

**Comment by niklasravnsborg** [comment]
@vzool Is it possible with pure mPDF to display the watermark only on one page?

**Comment by vzool** [comment]
@niklasravnsborg  Aha, I think your old version [1.2.0](https://github.com/niklasravnsborg/laravel-pdf/tree/v1.2.0) is better one.
It is just needs an `instance()` function to access all low level function that provided by **mPDF** Library which I added is [here](https://github.com/vzool/laravel-pdf/blob/v1.5/src/LaravelPdf/PdfWrapper.php#L177).

Thanks for your replay
