### ISSUE TITLE
Does not show numbers in Persian

### ISSUE THREAD

**Issue by mehran-akb** [niklasravnsborg/laravel-pdf#165]
hi.
i used this library and its ok
but i cant fix numbers to persian font
![Capture](https://user-images.githubusercontent.com/53018380/80972652-9d320a00-8e33-11ea-9dd4-6496ddf2b7ac.JPG)
config :
![Capture](https://user-images.githubusercontent.com/53018380/80972850-d9fe0100-8e33-11ea-8c14-8243916e7d2e.JPG)

but when i comment useOTL The Number are correct but words show clutter
![Capture](https://user-images.githubusercontent.com/53018380/80973379-8a6c0500-8e34-11ea-96b9-5082fdeade51.JPG)
![Capture](https://user-images.githubusercontent.com/53018380/80973443-a1125c00-8e34-11ea-8373-a32bc0e3d929.JPG)

**Comment by msadeghyan1996** [comment]
hi @mehran-akb .
for persian number's you should use IRANSans(FaNum).ttf font.

**Comment by miladparsi** [comment]
hi guys i used this package and still not getting any persian character
help me please :(

**Comment by miladparsi** [comment]
> hi @mehran-akb .
> for persian number's you should use IRANSans(FaNum).ttf font.

hi guys i used this package and still not getting any persian character
help me please :(

**Comment by msadeghyan1996** [comment]
Hello @miladparsi 
use most set config/pdf.php like below code :
`
return [
	'mode'                  => 'utf-8',
	'format'                => 'A4',
	'author'                => '',
	'subject'               => '',
	'keywords'              => '',
	'creator'               => 'Dr-Code.ir',
	'display_mode'          => 'fullpage',
	'tempDir'               => base_path('../temp/'),
	'font_path' => base_path('storage/fonts/'),
	'font_data' => [
		'iransans' => [
			'R'  => 'IRANSansFa.ttf',    // regular font
			'B'  => 'IRANSansFaBold.ttf',    // Bold font
			'useOTL' => 0xFF,    // required for complicated langs like Persian, Arabic and Chinese
			'useKashida' => 75,  // required for complicated langs like Persian, Arabic and Chinese
		],
	]
];
`
don't forget enable "useOTL" option. useOTL for persian&arabic&chinese lenguage.

**Comment by miladparsi** [comment]
> Hello @miladparsi
> use most set config/pdf.php like below code :
> 
> ```
> return [
> 	'mode'                  => 'utf-8',
> 	'format'                => 'A4',
> 	'author'                => '',
> 	'subject'               => '',
> 	'keywords'              => '',
> 	'creator'               => 'Dr-Code.ir',
> 	'display_mode'          => 'fullpage',
> 	'tempDir'               => base_path('../temp/'),
> 	'font_path' => base_path('storage/fonts/'),
> 	'font_data' => [
> 		'iransans' => [
> 			'R'  => 'IRANSansFa.ttf',    // regular font
> 			'B'  => 'IRANSansFaBold.ttf',    // Bold font
> 			'useOTL' => 0xFF,    // required for complicated langs like Persian, Arabic and Chinese
> 			'useKashida' => 75,  // required for complicated langs like Persian, Arabic and Chinese
> 		],
> 	]
> ];
> ```
> 
> don't forget enable "useOTL" option. useOTL for persian&arabic&chinese lenguages.

hi
im going confused!
i tried what you said but agaun didnt work for me
here is my code : 
`return [
    'mode'                  => 'utf-8',
    'format'                => 'A4',
    'author'                => '',
    'subject'               => '',
    'keywords'              => '',
    'creator'               => 'Dr-Code.ir',
    'display_mode'          => 'fullpage',
    'tempDir'               => base_path('../temp/'),
    'font_path' => base_path('public/dist/fonts/ttf/'),
    'font_data' => [
        'iransans' => [
            'R'  => 'IRANSansWeb.ttf',    // regular font
            'B'  => 'IRANSansFaBold.ttf',    // Bold font
            'useOTL' => 0xFF,    // required for complicated langs like Persian, Arabic and Chinese
            'useKashida' => 75,  // required for complicated langs like Persian, Arabic and Chinese
        ],
    ]
];`
and my fonts are in public/dist/fonts/ttf/IRANSansWeb.ttf

what im doing wrong?

**Comment by mehran-akb** [comment]
@msadeghyan1996 
@miladparsi 
use of FaNum Fonts didnt work for me and i test a lot of fonts.
i solved this issue by convert numbers.
i post answer in stackoverflow
https://stackoverflow.com/questions/61594142/persian-numbers-in-niklasravnsborg-laravel-pdf

**Comment by miladparsi** [comment]
> @msadeghyan1996
> @miladparsi
> use of FaNum Fonts didnt work for me and i test a lot of fonts.
> i solved this issue by convert numbers.
> i post answer in stackoverflow
> https://stackoverflow.com/questions/61594142/persian-numbers-in-niklasravnsborg-laravel-pdf

yes i saw your post there yesterday
can you help me wuth my pdf.php?
please read my last reply

**Comment by mehran-akb** [comment]
@miladparsi 
what is your problem?
just numbers??

**Comment by miladparsi** [comment]
@mehran-akb
my pdf doesnt show persian characters
i put my code above

**Comment by msadeghyan1996** [comment]
@miladparsi 
do you copy font file's in to public/dist/fonts/ttf/??
in my config i set font path in to 'font_path' => base_path('storage/fonts/'), folder and copy all font file's int to this path.

**Comment by miladparsi** [comment]
@msadeghyan1996 
no i didnt do that
how should i do that?

**Comment by msadeghyan1996** [comment]
in you'r config file : 'font_path' => base_path('public/dist/fonts/ttf/')
so you most copy font file's in to 'public/dist/fonts/ttf' path.
do this and test.

**Comment by miladparsi** [comment]
@msadeghyan1996
they are already there :( 
![Capture](https://user-images.githubusercontent.com/64780571/83961898-fd8dee80-a8ac-11ea-99dd-4c749ba3ea16.PNG)

**Comment by mehran-akb** [comment]
@miladparsi 
your code seems correct
please use exactly this font which i attached
because i haved problem for one font but download from 2 place.

[IRANSansWeb1.zip](https://github.com/niklasravnsborg/laravel-pdf/files/4741476/IRANSansWeb1.zip)

**Comment by msadeghyan1996** [comment]
it's interesting!
add below code in you pdf html code : 
```
<?php
    header("Content-type: text/css; charset: UTF-8");
?>
```
and 
```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
```
and use 
```
font-family: 'iransans';
```
it's the final solution from me  :D

**Comment by miladparsi** [comment]
yes it fucking worked !!!!
thanks to both of you guys 
@mehran-akb 
@msadeghyan1996 
thank you for your time

**Comment by erfansahaf** [comment]
It seems the problem is solved. Thanks to who contributed.
