### ISSUE TITLE
Temporary files directory "project/../temp/" is not writable

### ISSUE THREAD

**Issue by hamedgasemi200** [niklasravnsborg/laravel-pdf#166]
I'm trying to use this package in my Laravel project using the following script, but I get this error: `Temporary files directory "project/../temp/" is not writable`

```       
$pdf = niklasravnsborg\LaravelPdf\Facades\Pdf::loadView("ShowPDF", $data);
return $pdf->stream("{$uuid}.pdf");
```
#### How can I change the temp directory?

**Comment by hamedgasemi200** [comment]
I should've published the config file.

```
php artisan vendor:publish
```

**Comment by Padi-dev-hoangdv** [comment]
I have same problem on server even with publish vendor

**Comment by MostafaHamedAbdelmasoud** [comment]
i get this error on server, can't figure out what should i do, however i changed the permission of this folder but it still not working!
