### ISSUE TITLE
[Help request] I get error during testing 'Undefined index: data'

### ISSUE THREAD

**Issue by andreich1980** [niklasravnsborg/laravel-pdf#17]
My code
```
public static function managePdf($view, $vars = [], $file = null)
{
	$pdf = PDF::loadView($view, $vars);

	if (request()->exists('save'))
		return Storage::put($file, $pdf->output($file))
			? 'PDF saved to ' . $file
			: null
		;
	return $pdf->download($file);
}
```

Everything works fine.

But when I run my phpunit test.
```
// there are two nested foreach-loops by `testings` and `clients`
// inside the inner loop I run a command
//dump(sprintf('/result/client-%d-testing-%d/%s?save', $client->id, $testing->id, $filename));
$this->get(sprintf('/result/client-%d-testing-%d/%s?save', $client->id, $testing->id, $filename))
    ->assertResponseOk()
    ->see('Pdf saved to ' . $filename);
```

I get an error:
> [2016-12-29 22:17:04] testing.ERROR: exception 'ErrorException' with message 'Undefined index: data' in D:\Dropbox\OpenServer\domains\testing-system\vendor\niklasravnsborg\mpdf\mpdf.php:10944
> Stack trace:
> #0 D:\Dropbox\OpenServer\domains\testing-system\vendor\niklasravnsborg\mpdf\mpdf.php(10944): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', 'D:\\Dropbox\\Open...', 10944, Array)
> #1 D:\Dropbox\OpenServer\domains\testing-system\vendor\niklasravnsborg\mpdf\mpdf.php(26283): mPDF->_putimages()
> #2 D:\Dropbox\OpenServer\domains\testing-system\vendor\niklasravnsborg\mpdf\mpdf.php(11325): mPDF->_putresources()
> #3 D:\Dropbox\OpenServer\domains\testing-system\vendor\niklasravnsborg\mpdf\mpdf.php(2142): mPDF->_enddoc()
> #4 D:\Dropbox\OpenServer\domains\testing-system\vendor\niklasravnsborg\mpdf\mpdf.php(9275): mPDF->Close()
> #5 D:\Dropbox\OpenServer\domains\testing-system\vendor\niklasravnsborg\laravel-pdf\src\LaravelPdf\PdfWrapper.php(74): mPDF->Output('', 'S')
> #6 D:\Dropbox\OpenServer\domains\testing-system\app\Testing.php(330): niklasravnsborg\LaravelPdf\PdfWrapper->output('1115_1019.pdf')
> #7 D:\Dropbox\OpenServer\domains\testing-system\app\Http\Traits\ManagingResults.php(68): App\Testing::managePdf('testings.result...', Array, '1115_1019.pdf')

If I use `dump` to print out the "bad" URL and follow the URL in a browser - everything is working fine Really rare I get an error about `unlink(some_tmp_png_image_in_the_vendor_folder): Access denied`. But I refresh the page and it disappears.

Did I do anything wrong?

**Comment by niklasravnsborg** [comment]
@andreich1980 Which version of this package are you using? Did you try to upgrade to the latest?

**Comment by andreich1980** [comment]
I didn't notice that the version in my composer was ^1.3 and your is 1.4
Changed to ~1.4 and somehow the problem disappeared. 
Thanks!

**Comment by niklasravnsborg** [comment]
@andreich1980 Nice! Glad that this fixed your problem ☺️
