### ISSUE TITLE
Border in PDF including header and footer.

### ISSUE THREAD

**Issue by veed76** [niklasravnsborg/laravel-pdf#173]
@niklasravnsborg 
I want to set this green border in PDF, does anybody has idea? how can I set this border? 

**Screenshots**
https://prnt.sc/t0z8v4

**Comment by niklasravnsborg** [comment]
@veed76 This is no support forum, please only submit bug reports via GitHub.

Regarding your question, look at the @page CSS selector and other print specific selectors. Maybe there is a way to set a border or an outline.

I will close the issue now.
