### ISSUE TITLE
exported pdf font family is not working

### ISSUE THREAD

**Issue by rsathya018** [niklasravnsborg/laravel-pdf#178]
Hi,

 i have integrated larvel pdf export it works fine.but the applied google font family is not working. Please find my code and give me the solution or mention mistakes that i have done with this. Thanks in advance !..
![Screenshot from 2020-07-27 16-19-04](https://user-images.githubusercontent.com/68851479/88535158-1a31e180-d027-11ea-9a17-0dba2ec8bc0b.png)

**Comment by niklasravnsborg** [comment]
Hey! You cannot use Google Fonts from the CDN. Please see: https://github.com/niklasravnsborg/laravel-pdf#custom-fonts
