### ISSUE TITLE
Failed to load PDF document.

### ISSUE THREAD

**Issue by alfligno** [niklasravnsborg/laravel-pdf#182]
Im testing the package but it got error while viewing the generated PDF,

```php
$pdf = PDF::loadView('pdf.colleage', $data);
return $pdf->save('colleage.pdf');
```

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Document</title>
</head>
<body>
	COLLEAGES
</body>
</html>

![image](https://user-images.githubusercontent.com/69491106/94508875-8dcdb600-0245-11eb-91d5-ff4637d2850f.png)


```

**Comment by alfligno** [comment]
Found a solution,
If I use stream it will display the pdf via route :)
Now in my case I have to download it via API, so I converted the stream to base64

```php
ob_start();
$pdf = PDF::loadView('pdf.document', [], []);
$pdf->save('php://output');
$pdfData = ob_get_contents();
ob_end_clean();
die("data:application/pdf;base64,".base64_encode($pdfData));
```

**Comment by Padi-dev-hoangdv** [comment]
> Found a solution,
> If I use stream it will display the pdf via route :)
> Now in my case I have to download it via API, so I converted the stream to base64
> 
> ```
> ob_start();
> $pdf = PDF::loadView('pdf.document', [], []);
> $pdf->save('php://output');
> $pdfData = ob_get_contents();
> ob_end_clean();
> die("data:application/pdf;base64,".base64_encode($pdfData));
> ```
> 
> ```js
> let $a = $("<a>");
> $a.attr("href",text);
> $("body").append($a);
> $a.attr("download","document.pdf");
> $a[0].click();
> $a.remove();
> ```

I have this error Temporary files directory "../temp/" is not writable in file vendor/mpdf/mpdf/src/Cache.php on line 17.
Do you know why?

**Comment by alfligno** [comment]
temp folder should exists relative to your laravel project, which means temp should exists with the same parent folder your project

parent-dir
- your-project
- temp
