### ISSUE TITLE
Header/Footer only for Specific Page or First Page

### ISSUE THREAD

**Issue by psycho3069** [niklasravnsborg/laravel-pdf#187]
Currently adding a header adds it to all pages. How can we add header for specific pages? The issue is necessary regarding margin issue as the header includes it's content above the default or specified margin. It is necessary for someone (specially in my case) to add a header only for first page which will show a date on top of the first page and also above the margin area.

**Comment by msadeghyan1996** [comment]
hi. see this #114
i hope that can help you
