### ISSUE TITLE
How Define a default page size/format by array - page will be 190mm wide x 236mm height ?

### ISSUE THREAD

**Issue by joglostudio** [niklasravnsborg/laravel-pdf#189]
How Define a default page size/format by array - page will be 190mm wide x 236mm height ?
$mpdf = new \Mpdf\Mpdf(['mode' => 'utf-8', 'format' => [190, 236]]);

**Comment by niklasravnsborg** [comment]
Hey @joglostudio, I'm sorry we can't provide support via issues here. I hope you find a way to get it to work. Always feel free to fork the repository!
