### ISSUE TITLE
Possible to integrate an FPDF script?

### ISSUE THREAD

**Issue by mtaki14** [niklasravnsborg/laravel-pdf#196]
I'm trying to add rotated repeating text as a background and I found an FPDF "Rotations" script [here](http://www.fpdf.org/en/script/script2.php) which achieves exactly what I want.

Is it possible to extend this mpdf library to include the above class/ functions and if yes how should I go about it?

Alternatively is there another way to achieve this sort of rotated text background?

**Comment by mtaki14** [comment]
The background should look like this
![image](https://user-images.githubusercontent.com/7987430/108195451-71f97c80-7120-11eb-9954-54aaececdb06.png)

**Comment by niklasravnsborg** [comment]
Hey @mtaki14, laravel-pdf is based on mpdf. Therefore you cannot integrate fpdf scripts.
