### ISSUE TITLE
javascript dose not work

### ISSUE THREAD

**Issue by amirmsj1374** [niklasravnsborg/laravel-pdf#198]
I convert a blade file to PDF through this package and When I wanted to draw a chart, I realized that even a simple JavaScript function would not work. for example:

```  document.getElementById('myTest').innerHTML = 'javascript dose not work';```

Whats the problem?
Has anyone had this problem before?

**Comment by erfansahaf** [comment]
This package does not execute javascript codes. Create an image of your chart and use it in your blade template instead.
