### ISSUE TITLE
WatermarkImage not working

### ISSUE THREAD

**Issue by lxkraken** [niklasravnsborg/laravel-pdf#2]
I had this working in mPDF outside of Laravel without a problem.

I can't get SetWatermarkImage() working regardless of whether I set showWatermarkImage to true. I even tried using the <watermark> HTML control tag  and it doesn't work either.

I did get the image to load using the Image() method, but that isn't really what I was I hoping for.

**Comment by niklasravnsborg** [comment]
@lxkraken Hey thanks for the issue but I currently don't have time to investigate... I hope I will find some time next week. Maybe you can try to solve this and submit a PR?

**Comment by shihabudheenf** [comment]
Any updates?  I got stuck there :( at the last moment

**Comment by niklasravnsborg** [comment]
@shihabudheenf Maybe you can figure this out. Still really busy... sorry :(

**Comment by shihabudheenf** [comment]
I fixed by updating your package code. :)   and now water mark is working fine but there is small issue that the text placing over watermark image is getting fade. may be issue mpdf.. don't know.

**Comment by niklasravnsborg** [comment]
@lxkraken @shihabudheenf I added the methods `setWatermarkImage` and `setWatermarkText` in https://github.com/niklasravnsborg/laravel-pdf/commit/b5238f810f47667ddd7dac2139da82ef051c3fcf.
