### ISSUE TITLE
content goes in front of page-header

### ISSUE THREAD

**Issue by splu0008** [niklasravnsborg/laravel-pdf#20]
When I try to add content, it goes in front of the page-header section, not below it.

**Comment by niklasravnsborg** [comment]
@splu0008 Can you send me an example or your code?

**Comment by splu0008** [comment]
Here is the code:
``` php
<htmlpageheader name="page-header">
    <div class="row">
        <div class="col-xs-5 col-xs-offset-1">
            <img src="{{ asset("/images/logo.png") }}"/> <br/>
            {{ \Carbon\Carbon::now()->format('d-m-Y') }}
        </div>
        <div class="col-xs-3 col-xs-offset-2">
            <div class="pull-right">
                <br/>
                {{ $worknumber->customer->company }}
            </div>
        </div>
        <hr/>
    </div>
</htmlpageheader>
<div class="row">
    <div class="col-xs-10 col-xs-offset-1">
        Geachte {{ $worknumber->customer->contact }}, Geachte heer,
    </div>
</div>
``` 

Which makes it look like this:
![image](https://cloud.githubusercontent.com/assets/21340484/21956103/4081bd44-da79-11e6-8547-c7c4065a85b8.png)

**Comment by andreich1980** [comment]
I had the same problem but I just increased top margin of content

**Comment by niklasravnsborg** [comment]
@splu0008 Yeah, @andreich1980 is correct. You have to increase the top margin.

Try this:

```
@page {
  margin-top: 20pt; /* or something else */
}
```

Let me know if this works.

**Comment by splu0008** [comment]
Is there a way to exept first page? I want the first page to be a cover page with margin 0 , and other pages to have a header and then a margin top. I have 2 separate files to accomplish this now. And cannot find a package that can merge pdf files that is compatible with mpdf.

**Comment by andreich1980** [comment]
@splu0008 have you tried htmlpageheader::first-child selector and set display:none? Maybe it would work.

**Comment by jvsplunder** [comment]
@andreich1980 Did you mean like this?
```css
htmlpageheader:first-child {
            display: none;
        }
```

**Comment by andreich1980** [comment]
@jvsplunder what about that http://stackoverflow.com/questions/24670208/mpdf-different-header-for-first-page

**Comment by jvsplunder** [comment]
@andreich1980 @niklasravnsborg fixed it
CSS
```css
        @page {
            header: otherpages;
            margin-top: 95pt;
        }

        @page :first {
            header: firstpage;
            margin-top: 0pt;
        }
```
HTML
```html
<htmlpageheader name="firstpage" style="display:none">
</htmlpageheader>
<htmlpageheader name="otherpages">
    <div class="row">
        <div class="col-xs-5 col-xs-offset-1">
            <img src="{{ asset("/images/logo.png") }}"/> <br/>
            {{ \Carbon\Carbon::now()->format('d-m-Y') }}
        </div>
        <div class="col-xs-3 col-xs-offset-2">
            <div class="pull-right">
                <br/>
                {{ $worknumber->customer->company }}
            </div>
        </div>
        <hr/>
    </div>
</htmlpageheader>
```

Thanks for the help!

**Comment by niklasravnsborg** [comment]
There you go, nice! 😄
