### ISSUE TITLE
Map rendering stopped working

### ISSUE THREAD

**Issue by MrWeb** [niklasravnsborg/laravel-pdf#206]
I always used this package but it recently stops rendering static map images gotten from [mapbox][2].

I thought the problem was mapbox so I tried [tomtom][3] but I still get the "X" of the image error.

If I manually place an image tag with an hardcoded url (ie: https://ichef.bbci.co.uk/images/ic/1200x675/p0698w66.jpg) it renders perfectly.

I recently did an upgrade so I tried downgrading it back to 4.0.0 but with no luck.
What could cause this issue?

  [1]: https://packagist.org/packages/niklasravnsborg/laravel-pdf
  [2]: https://account.mapbox.com/
  [3]: https://developer.tomtom.com/content/map-display-api-explorer#/Raster/get_map__versionNumber__staticimage

**Comment by niklasravnsborg** [comment]
Hey @MrWeb, I'm sorry we can't provide support via issues here. I hope you find a way to get it to work. If you want to report a bug, please open an issue using the bug template.
