### ISSUE TITLE
Some CSS styles doesn't work properly

### ISSUE THREAD

**Issue by fouadfawzi** [niklasravnsborg/laravel-pdf#209]
I'm trying use `text-decoration-line: line-through;` but it doesn't work in pdf while it works fine in html 
 HTML version:
 
![Screen Shot 2021-09-08 at 11 06 53 AM](https://user-images.githubusercontent.com/25510860/132480913-3f8737e8-2b71-4095-bd9c-6249bab3ff82.png)

PDF version:

![Screen Shot 2021-09-08 at 11 07 11 AM](https://user-images.githubusercontent.com/25510860/132480968-f86af2e4-c77e-4ab5-a650-68929b590421.png)
  
  any recommendation ?
  @niklasravnsborg

**Comment by niklasravnsborg** [comment]
Hey, I'm sorry we can't provide support via issues here. I hope you find a way to get it to work. Always feel free to fork the repository!

**Comment by niklasravnsborg** [comment]
Hey, I'm sorry we can't provide support via issues here. I hope you find a way to get it to work.
