### ISSUE TITLE
PHP 7.1 A non-numeric value encountered

### ISSUE THREAD

**Issue by v-wolf** [niklasravnsborg/laravel-pdf#21]
Hi, PHP 7.1 return error:

in mpdf.php line 30648
at HandleExceptions->handleError('2', 'A non-numeric value encountered', '/.../vendor/mpdf/mpdf/mpdf.php', '30648', array('size' => '0', 'maxsize' => '190.001555556', 'fontsize' => '3.175', 'usefontsize' => false)) in mpdf.php line 30648

**Comment by splu0008** [comment]
I had the same problem, it was a img with class img-responsive. When I removed the class it worked.

**Comment by v-wolf** [comment]
I am not use any image.
Here is same problem 
https://github.com/dompdf/dompdf/issues/1272
https://github.com/dompdf/dompdf/pull/1331#issuecomment-270331481

**Comment by niklasravnsborg** [comment]
@v-wolf I think this is a `dompdf` specific issue and you have to watch the issues there. Anyway, can you send the code that is producing this error?

**Comment by niklasravnsborg** [comment]
@v-wolf I think this is a `dompdf` specific issue and you have to watch the issues there. Anyway, can you send the code that is producing this error?

**Comment by v-wolf** [comment]
@niklasravnsborg I have one more time check my CSS and remove {position: absolute;} and this work now fine. Thanks )))

**Comment by niklasravnsborg** [comment]
Awesome 🙌

**Comment by AymanElshehawy** [comment]
The problem here is in E_WARNING exception in PHP 7:
https://stackoverflow.com/a/42044413

I solved this problem just by replacing line 89:
$errorlevel = error_reporting($errorlevel & ~E_NOTICE);
with:
$errorlevel = error_reporting($errorlevel & ~(E_NOTICE|E_WARNING));
