### ISSUE TITLE
QRcode on the PDF

### ISSUE THREAD

**Issue by heshanmax** [niklasravnsborg/laravel-pdf#215]
HI i'm trying to insert a QRcode inthe PDF

{!! DNS2D::getBarcodeHTML('4445645656', 'QRCODE',2,2); !!}

but it gives blank pdf

**Comment by niklasravnsborg** [comment]
Hello, thanks for reporting this.

Please use the bug report issue template when reporting a bug so we can reproduce it easily. Either close this issue and create a new one or edit your original post.

Thank you!

**Comment by msadeghyan1996** [comment]
hi. i think you should save barcode in image file and use image path in pdf.
