### ISSUE TITLE
how to fix this problem?

### ISSUE THREAD

**Issue by karma77451180** [niklasravnsborg/laravel-pdf#222]
Declaration of Mpdf\Mpdf::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void

**Comment by niklasravnsborg** [comment]
Hey, I'm sorry we can't provide support via issues here. I hope you find a way to get it to work. Always feel free to fork the repository!
