### ISSUE TITLE
Laravel 5.3 to 5.4 upgrade issue Missing argument 2 for niklasravnsborg\LaravelPdf\PdfServiceProvider::niklasravnsborg\LaravelPdf\{closure}(),

### ISSUE THREAD

**Issue by umairali** [niklasravnsborg/laravel-pdf#23]
Laravel 5.3 to 5.4 upgrade issue

ErrorException in PdfServiceProvider.php line 28:
Missing argument 2 for niklasravnsborg\LaravelPdf\PdfServiceProvider::niklasravnsborg\LaravelPdf\{closure}(), called in C:\umairali\htdocs\beeah-laravel\vendor\laravel\framework\src\Illuminate\Container\Container.php on line 678 and defined

**Comment by umairali** [comment]
Change file vender\niklasravnsborg\LaravelPdf\PdfServiceProvider line 28 code 

$this->app->bind('mpdf.wrapper', function($app, $cfg) {
	return new PdfWrapper();
});

to 

$this->app->bind('mpdf.wrapper', function($app) {
	return new PdfWrapper();
});

**Comment by umairali** [comment]
If I use the code like example 1 it's working.

**Example 1**
```
PDF::loadView('pdf.invoice', $data)->save($pdfFilePath);
```

```
$this->app->bind('mpdf.wrapper', function($app) {
    return new PdfWrapper();
});
```

but if I add the second custom style parameter its showing same above error.

**Example 2**
```
PDF::loadView('pdf.invoice', $data, [], [
      'margin_left' => 0
])->save($pdfFilePath);
```

vender\niklasravnsborg\LaravelPdf\PdfServiceProvider line 28 code

```
$this->app->bind('mpdf.wrapper', function($app, $cfg) {
    return new PdfWrapper();
});
```

**Comment by niklasravnsborg** [comment]
@umairali I will make this package Laravel 5.4 ready as soon as our company upgrades. I think this will be in a few days. Please hold on

**Comment by umairali** [comment]
ok thanks

**Comment by melihovv** [comment]
Until my pull will be merged, you can use my fork
```json
"require": {
    "niklasravnsborg/laravel-pdf": "dev-master"
},
"repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/melihovv/laravel-pdf"
    },
],
```

**Comment by niklasravnsborg** [comment]
Sorry for the long wait. I'm procrastinating... Hope to get this done soon

**Comment by niklasravnsborg** [comment]
Did it in https://github.com/niklasravnsborg/laravel-pdf/releases/tag/v1.5.0!
