### ISSUE TITLE
convert html to pdf directly without view

### ISSUE THREAD

**Issue by mshanak** [niklasravnsborg/laravel-pdf#24]
hello
how to convert html content into pdf without using a view file? 

eg:
```
$mpdf = new \Mpdf\Mpdf();
$mpdf->WriteHTML('<h1>Hello world!</h1>');
$mpdf->Output();
```

**Comment by andreich1980** [comment]
There's a loadHTML method
https://github.com/niklasravnsborg/laravel-pdf/blob/master/src/LaravelPdf/PdfWrapper.php#L16
But I don't have an example for you

**Comment by mshanak** [comment]
thank you 
it works :+1: 

```

Route::get('/pdf', function(){
	
	$pdf = PDF::loadHTML('<h1>Hello مرحبا שלום</h1>');
    return $pdf->stream('news.pdf');

});

```

**Comment by andreich1980** [comment]
With my pleasure.
Could you please close the issue by yourself?

**Comment by mshanak** [comment]
done

**Comment by niklasravnsborg** [comment]
@mshanak @andreich1980 Nice guys! Glad you worked this out 👍
