### ISSUE TITLE
Extend CSS Support

### ISSUE THREAD

**Issue by Rav23** [niklasravnsborg/laravel-pdf#26]
First of all, Well done on an awesome package.

I want to find out if there's a way to make this package work with css frameworks such as Bootstrap...

Regards
O.M

**Comment by niklasravnsborg** [comment]
@Rav23 Sorry for the later answer. You can try to use styling from frameworks and they will surely work fine. Just link the normal CSS file. My guess would be that the grid will not work as expected. For Layout just use a table. This might feel weird but also is the "way to go" layouting method in text editing software for fixed width pages.
