### ISSUE TITLE
Set custom config through a function

### ISSUE THREAD

**Issue by michael-roewin** [niklasravnsborg/laravel-pdf#28]
Hi,

Great work on making this wrapper! :)

I just want to ask if there is a way to set the config through a function?

Eg.

function generate_pdf() {
    $data = [
        'foo' => 'bar'
    ];
    $pdf = PDF::loadView('pdf.document', $data);
    $pdf->SetProtection(['copy', 'print'], '', 'pass');
    **$pdf->setConfig([
        'mode'                 => '',
        'format'               => 'A4',
        'default_font_size'    => '12',
        'default_font'         => 'sans-serif',
        'margin_left'          => 10,
        'margin_right'         => 10,
        'margin_top'           => 10,
        'margin_bottom'        => 10,
        'margin_header'        => 0,
        'margin_footer'        => 0,
        'orientation'          => 'P',
        'title'                => 'Laravel mPDF',
        'author'               => '',
        'watermark'            => '',
        'show_watermark'       => false,
        'watermark_font'       => 'sans-serif',
        'display_mode'         => 'fullpage',
        'watermark_text_alpha' => 0.1
    ]);**

    return $pdf->stream('document.pdf');
}

Cheers!
Michael

**Comment by michael-roewin** [comment]
Hi, 

I read the code in the src/LaravelPdf/PDFWrapper.php and I found out that there's a way for this to work.

$config = [
    'format'                => 'A4',
    'margin_left'           => 12,
    'margin_right'          => 12,
    'margin_top'            => 32,
    'margin_bottom'         => 10,
    'margin_header'         => 10,
    'margin_footer'         => 10,
];

return  PDF::loadView('pdf', ['data' => $data], [], $config)->stream('download.pdf');

**Comment by niklasravnsborg** [comment]
@michael-roewin Yep! Awesome 😌

**Comment by michael-roewin** [comment]
You might want to put this in the readme section just in case other developers want to use this kind of approach..! :)

**Comment by niklasravnsborg** [comment]
@michael-roewin I agree: d490a6ac8c1e8d586b03b56f6fe6bb47b7c91a91
