### ISSUE TITLE
Image not rendering in Pdf & taking too much time to generate Pdf 

### ISSUE THREAD

**Issue by srikanth240369** [niklasravnsborg/laravel-pdf#3]
If we give only Plain text it is working , But when you include img tags it is not working

![http localhost 8000 test failed to load](https://cloud.githubusercontent.com/assets/12655260/16077269/76388d48-3315-11e6-970c-b8260a5822c8.png)

**Comment by niklasravnsborg** [comment]
@srikanth240369 Hey there can you give me a code snippet?

**Comment by niklasravnsborg** [comment]
@srikanth240369 Maybe this is a problem with RAM? I recently had this when the image was to big but this is not something we can catch. We had to make sure the images are small enough.
