### ISSUE TITLE
Arabic font issue

### ISSUE THREAD

**Issue by umairali** [niklasravnsborg/laravel-pdf#30]
Arabic font not connected and its showing like this

![captdddure](https://cloud.githubusercontent.com/assets/5318005/23337997/6a2f14b4-fc18-11e6-8078-572178d61c20.PNG)

The right word is 
الإسم

**Comment by umairali** [comment]
To fix this issue with just add 2 new parameters in Arabic fonts array

```
'useOTL' => 0xFF,
'useKashida' => 75,
```

```
 'arabic-font' => [
            'R'  => 'arabic-font.ttf',    // regular font
            'B'  => 'arabic-font.ttf',          // optional: bold font
            'I'  => 'arabic-font-Light.ttf',    // optional: italic font
            'BI' => 'arabic-font.ttf',           // optional: bold-italic font
            'useOTL' => 0xFF,
            'useKashida' => 75,
        ]
```

**Comment by niklasravnsborg** [comment]
@umairali Okay I will look at this

**Comment by erfansahaf** [comment]
@umairali Can we define custom font in `config/pdf.php` ? Or we should edit mpdf library by ourselves?

**Comment by niklasravnsborg** [comment]
@erfansahaf Yes, you can define custom fonts like this: https://github.com/niklasravnsborg/laravel-pdf#custom-fonts

**Comment by erfansahaf** [comment]
@niklasravnsborg I have read the README more than 5 times but I don't know why I didn't see custom font section even once! 😐 Thanks.

**Comment by niklasravnsborg** [comment]
@erfansahaf No problem!

**Comment by niklasravnsborg** [comment]
Awesome! This can be closed now :)

**Comment by sinahosseini76** [comment]
i have problem with persian fonts 
i try lots of fonts but don't work
please help

**Comment by erfansahaf** [comment]
@sinahosseini76 Which font do you use? Have you set the OTL options in your configs?

**Comment by Asim1khan** [comment]
arabic text not show properly like in place of 1 it take the arabic 1 and 0.00 before the point of 0 not showing  please help me

**Comment by mranonyms022** [comment]
Arabic fonts are working 
I Need to show Arabic font now What Will do please help

**Comment by mranonyms022** [comment]
> arabic text not show properly like in place of 1 it take the arabic 1 and 0.00 before the point of 0 not showing please help me [Subscription Details (2).pdf](https://github.com/niklasravnsborg/laravel-pdf/files/9401303/Subscription.Details.2.pdf)

Will you please tell me how you solved arabic font issue.
