### ISSUE TITLE
Call to undefined method niklasravnsborg\LaravelPdf\Facades\Pdf::SetTitle()

### ISSUE THREAD

**Issue by yahmez00** [niklasravnsborg/laravel-pdf#31]
Hey there,

Trying to use your library, but whenever I generate a PDF I get the following error:

`Call to undefined method niklasravnsborg\LaravelPdf\Facades\Pdf::SetTitle()`

I'm using the example code from your readme.md, so nothing fancy. Have tried it on a view other views with no luck either.

Sorry I don't have more information to provide, I simply followed the 'Installation' then 'Basic Usage' steps and am unable to go any further.

Thanks for any help.

**Comment by yahmez00** [comment]
Hmm, so just tried running the library on a fresh installation of Laravel and everything worked fine. However on my exisiting project I'm getting the error above. Will see if I can find any solution.

**Comment by yahmez00** [comment]
Okay this may been an issue relating to the naming of the facade. I was pulling it in as `'mPDF' => niklasravnsborg\LaravelPdf\Facades\Pdf::class`, but it didn't like that for some reason. Having it named as just 'PDF', 'PDFm' or 'LaravelPDF' works just fine.

**Comment by niklasravnsborg** [comment]
@yahmez00 Awesome, glad you fixed this for yourself.
