### ISSUE TITLE
Can't save to server

### ISSUE THREAD

**Issue by mladenSta** [niklasravnsborg/laravel-pdf#32]
Hi!

The only issue for me is that I cant save PDF document to disk. I tried with:
$pdf->Output('filename.pdf','F');
It does not save to any directory.
Thank you!

**Comment by niklasravnsborg** [comment]
@mladenSta Is there a error message?

**Comment by niklasravnsborg** [comment]
Please try this: `$pdf->save($filepath);`

**Comment by mladenSta** [comment]
It works with $pdf->save($filepath);.
Thank you very much.
