### ISSUE TITLE
IE11 can't save a pdf with specific name

### ISSUE THREAD

**Issue by HoneyKumar** [niklasravnsborg/laravel-pdf#33]
Hi,

I am using laravel 5.2. I am trying to stream a pdf with specific name it is working on chrome but not working on Interet explorer

**Comment by niklasravnsborg** [comment]
@HoneyKumar If it's working on Chrome I guess this is a problem with IE. Do you have an error log?

**Comment by HoneyKumar** [comment]
yes it is working on chrome what is happening is when we pass pdf name in stream function and when we click on download it saves pdf with same name passed in stream but in IE it is saving it by last string in url

**Comment by niklasravnsborg** [comment]
@HoneyKumar So it works but it doesn't stream it?
