### ISSUE TITLE
Error "A non-numeric value encountered"

### ISSUE THREAD

**Issue by deepslam** [niklasravnsborg/laravel-pdf#36]
Hello!

Thank you for this package.
I've installed it but with PHP 7.1.1 I've encountered with error "A non-numeric value encountered".
As I read that's because you use mpdf 6, how can I replace it on mpdf 7?
Thank you!

Kind Regards, Dmitry.

**Comment by niklasravnsborg** [comment]
From what I know mpdf 7 is still in beta. So we have to wait a little bit til I can upgrade
