### ISSUE TITLE
When using htmlpageheader, A non-numeric value encountered occurs.

### ISSUE THREAD

**Issue by larryu** [niklasravnsborg/laravel-pdf#37]
When using htmlpageheader, I have data passed to the view,  and it gives me the error of A non-numeric value encountered. If I don't pass data to the header view, it works fine.
Any suggestion?

**Comment by niklasravnsborg** [comment]
Hey @larryu! May you send me a screenshot of the error?

**Comment by Rav23** [comment]
This error is related to mpdf itself and php 7.1. There's a fork of the mpdf class that solves this issue.

**Comment by niklasravnsborg** [comment]
So this has nothing to do with this package - closed
