### ISSUE TITLE
Html image tag in htmlpageheader

### ISSUE THREAD

**Issue by HerlyOlivares** [niklasravnsborg/laravel-pdf#38]
Hi @niklasravnsborg, my question is if in the view you can place an image tag in html, such as a logo on an invoice, since placing it inside the htmlpageheader generates a maximum execution time error

**Comment by niklasravnsborg** [comment]
Sure! An `<img>` inside the the view should work without problems. Let me know if you are lucky. :)

**Comment by HerlyOlivares** [comment]
Thanks @niklasravnsborg  for your time, of course, when implementing it works, but by placing the src, this way src = "{{asset ('images / image.jpg')}}" does not process it and it generates an error, If I put the img without src works

**Comment by niklasravnsborg** [comment]
`asset()` is not a function from what I know. Maybe try this: https://laravel.com/docs/5.4/helpers#method-public-path

**Comment by niklasravnsborg** [comment]
@OAmor Debug it by generating the markup without MPDF. Use `{{asset ('images / image.jpg')}}` within the template and look whether it gives you an error.

**Comment by OAmor** [comment]
> @OAmor Debug it by generating the markup without MPDF. Use `{{asset ('images / image.jpg')}}` within the template and look whether it gives you an error.

thank u for the response 
when i use only the `{{asset ('images / image.jpg')}}` it gives me the path to my image and it works fine the problem here is with the img tag because even when i tried `<img src="my/path/images/image.png">` the same problem appear so i think that it can't read an external image
