### ISSUE TITLE
facade cannot be found

### ISSUE THREAD

**Issue by geraldarcega** [niklasravnsborg/laravel-pdf#39]
Hi! We're getting undefined `niklasravnsborg\LaravelPdf\Facades\Pdf`. We just follow the instructions in the Read.me, and just like other package we add the service provider and facade in the app.php.

**Comment by niklasravnsborg** [comment]
Can you please send me a screenshot of the error message?

**Comment by geraldarcega** [comment]
Hey @niklasravnsborg! We've already fixed the problem. We're having a bad time on our server set up because the admin does not allow composer to have access on internet, so we're just using it for dumping auto-loads. Based on our current set up, we just copy/paste packages from our dev instance to testing server. I know, it really sucks! LOL!

Anyway, my colleague forgot to copy essential packages to testing server that's why we encounter the error.

Thanks for the quick response!
