### ISSUE TITLE
Error with Laravel 5.0.*

### ISSUE THREAD

**Issue by atefBB** [niklasravnsborg/laravel-pdf#4]
Hi, I'm trying to install this package with laravel 5.0.\* and composer can't get the right version of the package, any ideas to fix it? Thanks.

**Comment by niklasravnsborg** [comment]
Hey @atefBB. Sorry for my late answer. Can you give me an error output?

**Comment by niklasravnsborg** [comment]
@atefBB Want to close this! Any updates?

**Comment by atefBB** [comment]
I don't know how or why? it's OK now !!
It's installed now.
thanks.

**Comment by niklasravnsborg** [comment]
@atefBB Ok 👍
