### ISSUE TITLE
Landscape not rendering

### ISSUE THREAD

**Issue by ilgala** [niklasravnsborg/laravel-pdf#40]
Hi everyone, I have to create a A5 paper with landscape orientation, but only portrait is rendered.

I'm using:

- PHP 7.1
- Laravel 5.4
- laravel-pdf 1.5

This is my code:

```php
$pdf = PDF::loadView('estimates.pdf.badge', ['estimate_row' => $estimate_row], [], ['orientation' => 'L', 'format' => 'A5']);
return $pdf->stream('badge.pdf');
```

**Comment by yahmez00** [comment]
Try using `"format"` => "A5-L"`. I know `"A4-L"` works, not sure about A5 however.

**Comment by pableiros** [comment]
I have changed the `format` value from the `config/pdf.php` file to `A5` and now it works. Now I have to figure out how to change it on runtime.
