### ISSUE TITLE
Getting permssion failed error on laravel 5.2 version

### ISSUE THREAD

**Issue by msankar1991** [niklasravnsborg/laravel-pdf#42]
```
ErrorException in ttfontsuni.php line 1264:
file_put_contents(/home/nextbrain/workspace/tijik_web/vendor/mpdf/mpdf/ttfontdata/dejavusanscondensed.GSUBGPOStables.dat): failed to open stream: Permission denied
```
**Used below code**
```
$pdf = PDF::loadHTML('pdf.document', $data);
$pdf->SetDirectionality('rtl');
return $pdf->stream('document.pdf');
```

![mpdf](https://user-images.githubusercontent.com/8719413/27963468-cd10c72a-6352-11e7-88c2-71bc2d82d64d.png)

**Comment by niklasravnsborg** [comment]
Hey! This seems to be a permission error. Try setting `chmod -R 777 /directory/shown/in/errormessage`. Let me know if this works! :)

**Comment by ksartnl** [comment]
I also had this error and used: `sudo chown -R user:group ttfontdata` with `sudo chmod -R ug+w ttfontdata` and it worked. User was the name for the site, group was nginx for me.
