### ISSUE TITLE
Image watermark doesn't show in first page

### ISSUE THREAD

**Issue by erfansahaf** [niklasravnsborg/laravel-pdf#45]
I'm trying to set an image watermark to my document but the first page of the rendered document doesn't contain image watermark.
Image watermark only shows after the first page:

View:
```php
<html lang="fa">
<body>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style type="text/css">
        body {
            font-family: yekan;
        }

        th {
            background: #2a2a2a;
            color: white;
            font-size: 22px;
            padding: 5px
        }

        td {
            font-size: 18px;
            padding: 10px 20px;
            text-align: center;
        }

        table {
            margin-left: auto;
            margin-right: auto;
        }

        h1 {
            margin: 20px 0 10px;
        }

        @page {
            header: page-header;
            footer: page-footer;
        }

        .text-center {
            text-align: center
        }
    </style>
</head>
<body>
<htmlpageheader name="page-header">
    <div><h1 class="text-center">سامانه آنلاین اعلام برنامه هفتگی دانشکده شمسی پور</h1></div>
    <hr>
</htmlpageheader>
<div>
    <?php $i = 0; $len = count($data); ?>
    @foreach($data as $day => $plans)
        <h2 class="text-center">برنامه دروس روز {{config('system.DAYS')[$day]}}</h2>
        <Br>
        <div>
            <table border="1">
                <thead>
                <tr>
                    <th>ساعت</th>
                    <th>نام درس</th>
                    <th>نام استاد</th>
                    <th>کلاس</th>
                </tr>
                </thead>
                <tbody>
                @foreach($plans as $plan)
                    <tr>
                        <td>{{$plan->start}} الی {{$plan->end}}</td>
                        <td>{{$plan->lname}}</td>
                        <td>{{$plan->teacher->name}} {{$plan->teacher->family}}</td>
                        <td>{{$plan->class}}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        @if($i != $len -1)
            <pagebreak></pagebreak>
        @endif
        <?php $i++; ?>
    @endforeach
</div>
</body>
</html>
```

Controller:
```php
$pdf = PDF::loadView('pdf.single', ["data" => $plans]);
$pdf->setWatermarkImage(public_path('img/logo1.png'));
$pdf->save(public_path('plans.pdf'));
```

**Comment by niklasravnsborg** [comment]
I can't reproduce this right now. Can you send me a screenshot of the first page and the second?

**Comment by erfansahaf** [comment]
First Page:
![image](https://user-images.githubusercontent.com/12012168/29210938-665bc588-7eab-11e7-82ec-bd78d88be333.png)

Second Page:
![image](https://user-images.githubusercontent.com/12012168/29210963-8014e392-7eab-11e7-9dd8-fef9806a3ead.png)

**Comment by erfansahaf** [comment]
@niklasravnsborg I added new pages to my document and then I realized that watermark image only works on the last page.

**Comment by niklasravnsborg** [comment]
Hmm, can you try setting the watermark in the config rather than in the controller?

**Comment by erfansahaf** [comment]
Is it possible to set image watermark in `pdf.php`? I changed `watermark` value to my image path and `show_watermark` to true but it showed my image path as text instead of an image.

**Comment by niklasravnsborg** [comment]
Got ya, i looked into the code... So it's currently not possible to set a watermark in config.
Maybe look at this https://mpdf.github.io/reference/mpdf-functions/setwatermarkimage.html and try to set your footer on each page...

```html
<htmlpagefooter name="page-footer"></htmlpagefooter>
```

try attaching this to the top of the `body`.

**Comment by erfansahaf** [comment]
No difference.
```php

            $pdf = PDF::loadView('pdf.complete', ["data" => $plans]);
            $pdf->mpdf->SetWatermarkImage(public_path('img/logo1.png'));
            $pdf->mpdf->showWatermarkImage = true;
```
Also I added footer to my view but it didn't work.

**Comment by thamibn** [comment]
i also have the same problem can anyone help us please

**Comment by niklasravnsborg** [comment]
@erfansahaf @thamibn I'm sorry but I just can recommend to not use a watermark image. It just won't work the way it is intended. :/

**Comment by erfansahaf** [comment]
@niklasravnsborg I think I would be better to keep this issue open, so other developers can check it. Maybe somebody had an idea to fix this.
Anyway, do you think this problem is caused by mPDF or this package? Did you try similar action with original mPDF before?

**Comment by niklasravnsborg** [comment]
I think this is caused by mPDF but I didn't have the time to investigate further.
Really appreciate your moderating around here, @erfansahaf! 👍 ☺️

**Comment by erfansahaf** [comment]
No problem. I'll work on it, just wish you had more time to contribute. ☺️

**Comment by erfansahaf** [comment]
@niklasravnsborg No problem, I'll work on it,
Wish you had more time to contribute. ☺️

**Comment by niklasravnsborg** [comment]
Hey! Does anybody have a solution for this? Does mpdf support a `background-image` on the `body` or `@page`?
