### ISSUE TITLE
How to insert a page break

### ISSUE THREAD

**Issue by andreich1980** [niklasravnsborg/laravel-pdf#48]
Hello. BTW, thanks for the package.

I want to insert a page break from inside my blade file. 

Like this
```
@foreach($documents as $document)

    {!! $document->body !!}

    // Here I want to break the page. Each document's body must start from a new page.

@endforeach
```
I want all documents in 1 file.

Is there a way to do it?

**Comment by erfansahaf** [comment]
You can break the page with `<pagebreak></pagebreak>` tag inside your Blade file.

**Comment by andreich1980** [comment]
@erfansahaf thank you. Wondering where did you find it? So I would find anything out later.

**Comment by erfansahaf** [comment]
Your welcome. This package is based on mPDF PHP class, so you can read [mPDF documentation](https://mpdf.github.io/) to find out anything you need as well as I found `<pagebreak> tag [here](https://mpdf.github.io/reference/html-control-tags/pagebreak.html).

**Comment by pankajToday** [comment]
> You can break the page with `<pagebreak></pagebreak>` tag inside your Blade file.

not working in 4.1
