### ISSUE TITLE
Landscape PDF Generation

### ISSUE THREAD

**Issue by jayendharp** [niklasravnsborg/laravel-pdf#5]
Hi, I'm trying to generate PDF. When I create a PDF with "Portrait" it works. On changing orientation to "Landscape", it still generates PDF with "Portrait" view.
Please help me resolve this.

**Comment by niklasravnsborg** [comment]
@jayendharp Sure. Did you change the settings in your `config/pdf.php`? You can refer to this: https://github.com/niklasravnsborg/laravel-pdf/blob/master/src/config/pdf.php

**Comment by jayendharp** [comment]
``

**Comment by jayendharp** [comment]
Yes. I changed `orientation` to 'L'. Still it doesn't work.
I'm not sure why.

**Comment by niklasravnsborg** [comment]
@jayendharp Okay I will look into it.

**Comment by jayendharp** [comment]
Hi @niklasravnsborg, did you get a chance to fix this issue?

**Comment by niklasravnsborg** [comment]
Hey @jayendharp! Good that you follow up. I honestly didn't have time to look into it till now. I'll do it right now.

**Comment by niklasravnsborg** [comment]
@jayendharp Try the following in your `pdf.php` config: Instead of using the `'orientation'` parameter add `'format' => 'A4-L',`.

Let me know if this works.

**Comment by jayendharp** [comment]
Thanks @niklasravnsborg. It works fine 👍

**Comment by niklasravnsborg** [comment]
@jayendharp 👍 Thats nice – glad that it works. For what project do you use this plugin? ☺️

**Comment by jayendharp** [comment]
It is a project to get the user profile information and display them with different templates.

**Comment by candrasetiadi** [comment]
Hi @niklasravnsborg , how if i want to make landscape for specific page? because in my project, sometimes need to potrait and sometimes need to landscape.

thanks

**Comment by niklasravnsborg** [comment]
@candrasetiadi Can you look in the https://mpdf.github.io/ docs? Maybe try with the @page CSS directive? Didn't had this requirement before...

**Comment by namixmedia** [comment]
It would be a good addition to give options per specific page.

**Comment by niklasravnsborg** [comment]
@namixmedia Should work with `@page` in CSS

**Comment by PeterLiptak** [comment]
@niklasravnsborg Hi! Is it possible to rotate page with specific size used? It this case i can not use 'format' => 'A4-L' as suggested above. My config file has configured **'format' => [70.1, 50.1],**. Thank you for your help.
