### ISSUE TITLE
Persian words showing dispatched

### ISSUE THREAD

**Issue by erfansahaf** [niklasravnsborg/laravel-pdf#50]
I'm trying to render multiple PDF documents using following codes:
```php
foreach($plans as $day => $plan){
	$pdf = PDF::loadView('pdf.single', ["day" => $day, "plans" => $plan]);
	$pdf->mpdf->SetWatermarkImage(public_path('img/logo1.png'));
	$pdf->mpdf->showWatermarkImage = true;
	if(file_exists(public_path('plans/plans-'.$day.'.pdf')))
		Storage::delete(public_path('plans/plans-'.$day.'.pdf'));
	$pdf->save(public_path('plans/plans-'.$day.'.pdf'));
}
```
But there is a problem. As you know, Persian (Farsi) language is similar to Arabic (in writing) and each word contains a couple of letters that should be patched to each other to shape the word. In the first rendered document everything is fine, but after that, every rendred document contains dispatched letters and it causes dispatched words.

Here is my first rendered document which is OK:
![image](https://user-images.githubusercontent.com/12012168/29210938-665bc588-7eab-11e7-82ec-bd78d88be333.png)

And my second document which is NOT OK:
![image](https://user-images.githubusercontent.com/12012168/29559727-228a580e-8745-11e7-8a56-2af6b5e5d469.png)

**Comment by niklasravnsborg** [comment]
@erfansahaf Can you try to reproduce this just with mPDF. I would think that this is a problem with their package. :/

**Comment by erfansahaf** [comment]
@niklasravnsborg I did the same with `mPDF` in pure PHP:
```php
require_once __DIR__ . '/vendor/autoload.php';
$mpdf = new mPDF();
$template = file_get_contents('template.html');
$mpdf->WriteHTML($template);
for($i = 0; $i< 3; $i++)
	$mpdf->Output(time()."-".rand(0,555555).".pdf", 'F');
```
But `mpdf` produced 3 PDFs with identical content which was not OK. So I tried this one:
```php
$template = file_get_contents('template.html');
$words = ['تست محتوا', 'یک رکورد', 'سلام نیکُلاس'];
foreach($words as $word){
	if(isset($mpdf))
		unset($mpdf);
	if(isset($final))
		unset($final);
	$mpdf = new mPDF();
	$final = str_replace('VAR', $word, $template);
	$mpdf->WriteHTML($final);
	$mpdf->Output(time()."-".rand(0,555555).".pdf", 'F');
}
```
And the result was exactly like this issue! So this problem is caused by `mpdf`, not this package. I'll open an issue in main `mpdf` [repository](https://github.com/mpdf/mpdf) and if I found any more detail, I'll update this.

**Comment by erfansahaf** [comment]
@niklasravnsborg It was a bug in `mPDF` and it's fixed in the development branch.
https://github.com/mpdf/mpdf/issues/486#issuecomment-331805162

**Comment by niklasravnsborg** [comment]
@erfansahaf So this will be fixed once I pull in the new dependency? This should also fix https://github.com/niklasravnsborg/laravel-pdf/issues/30, right?

**Comment by erfansahaf** [comment]
@niklasravnsborg I think if you use `dev` branch in your package's composer file for `mpdf` dependency, it will be OK.
Also, #30 is not related to this issue. That's a part of font configuration. I'll covert in a new PR.

**Comment by niklasravnsborg** [comment]
@erfansahaf Hey we have mpdf 7 now. May you look weather it fixed this issue? Would be super nice. Cheers 😎

**Comment by erfansahaf** [comment]
@niklasravnsborg Cool! 👍  I'm a little busy right now but I'll get into it in a month...

**Comment by 1razzaghi** [comment]
use this option on your font data array when adding font to custom_font_data : 
`'useOTL' => 0xFF,
            'useKashida' => 75,
            'unAGlyphs' => true,`

**Comment by erfansahaf** [comment]
@1razzaghi Did you read this issue carefully? Those options had been set and first rendered document was ok. The problem will happen when you use it in a loop, please read the issue once again.

**Comment by 1razzaghi** [comment]
i test your problem with laravel-pdf version 2 and mpdf 7 
no problem on the 100 loop(for loop)
with titr font and **yekan** font as you are fixing it's problem(gdef table) on [irfont](http://irfont.ir/fonts/%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D9%86%D8%B3%D8%AE%D9%87-%D8%AC%D8%AF%DB%8C%D8%AF-%D9%81%D9%88%D9%86%D8%AA-%D8%A8%DB%8C-%DB%8C%DA%A9%D8%A7%D9%86-b-yekan) and having no problem on 100 file saved on my pc and not dispatched

are you using the latest version?

**Comment by erfansahaf** [comment]
@1razzaghi Oh no, I haven't tested mpdf 7 yet, this problem was on mpdf 6. The problem seems has fixed in the new version. I'll test it by myself and if it is ok, this issue can get closed.

**Comment by Mekaeil** [comment]
> use this option on your font data array when adding font to custom_font_data :
> `'useOTL' => 0xFF, 'useKashida' => 75, 'unAGlyphs' => true,`

Many thanks. it was useful.
