### ISSUE TITLE
Custom Fonts Not Work

### ISSUE THREAD

**Issue by hatamiarash7** [niklasravnsborg/laravel-pdf#51]
hi

i can't use custom font as follow ( for UTF-8 / Persian ) : 

	'custom_font_path' => public_path('/fonts/'),
	'custom_font_data' => [
		'pdfFont' => [
			'R'  => 'mine.ttf',   
		]
	]

or change `default_font' in **pdf.php** file

nothing changed

**Comment by erfansahaf** [comment]
Persian fonts are supported.
Please before opening a new issue, check the old ones:

https://github.com/niklasravnsborg/laravel-pdf/issues/30

**Comment by hbsoftco** [comment]
I installed laravel-pdf package, but i have not pdf.php file in my config folder!!!!
everything is fine, but custom font is not working for me!

**Comment by erfansahaf** [comment]
@hbsoftco This package supposed to have the publish artisan command but it doesn't. So you have to copy pdf.php file from vendor/niklasravnsbor/laravel-pdf/src/config/pdf.php file into your app config directory manually.
Maybe later I send a pull request to fix this.

**Comment by erfansahaf** [comment]
@hatamiarash7 Please close the issue dude, it's already solved!
