### ISSUE TITLE
Showing Error With Php 7.1

### ISSUE THREAD

**Issue by umairali** [niklasravnsborg/laravel-pdf#53]
I am trying to update composer php vesion 5.6 top 7.1 but mpdf showing error message

`  Problem 1

    - mpdf/mpdf v6.1.4 requires php ^5.4.0 || 7.0.* -> your PHP version (7.1.9) does not satisfy that requirement.

    - Installation request for mpdf/mpdf v6.1.4 -> satisfiable by mpdf/mpdf[v6.1.4].`

**Comment by LordRahl90** [comment]
try to ignore the platform requirement by adding flag --ignore-platform-reqs

**Comment by niklasravnsborg** [comment]
@umairali Did this work for you?

**Comment by niklasravnsborg** [comment]
Probably a duplicate of https://github.com/niklasravnsborg/laravel-pdf/issues/52, right? Closing this
