### ISSUE TITLE
Auto publishing config file instead of copying manually

### ISSUE THREAD

**Issue by erfansahaf** [niklasravnsborg/laravel-pdf#56]
In this project, you should copy `pdf.php` (located on `laravel-pdf/src/config/pdf.php` file into your application config folder manually but it has to be published automatically by running `php artisan vendor:publish` command.
I opened this issue for those have the same question. Don't worry, I'll send a PR to fix it.

**Comment by niklasravnsborg** [comment]
Closed by: https://github.com/niklasravnsborg/laravel-pdf/pull/57
