### ISSUE TITLE
use French and Arabic in the same document

### ISSUE THREAD

**Issue by mohand85** [niklasravnsborg/laravel-pdf#58]
I use an Arabic font, but if I try to use words in French in the same document, they do not appear
here is my configuration

return [
    'mode' => 'utf-8',
    'format' => 'A4',
    'default_font_size' => '16',
    'default_font' => 'othmane',
    'margin_left' => 5,
    'margin_right' => 5,
    'margin_top' => 5,
    'margin_bottom' => 5,
    'margin_header' => 0,
    'margin_footer' => 0,
    'orientation' => 'P',
    'title' => '',
    'author' => '',
    'watermark' => '',
    'show_watermark' => false,
    'watermark_font' => 'sans-serif'
    'display_mode' => 'fullpage',
    'watermark_text_alpha' => 0.1,
    'custom_font_path' => base_path ('/ resources / fonts /'), do not forget the trailing slash!
    'custom_font_data' => [
        'othmane' => [
            'R' => 'UthmanTN1-Ver10.otf',
            'useOTL' => 0xFF,
     'useKashida' => 75, // regular font
       
        ]
    ]
];

**Comment by niklasravnsborg** [comment]
@mohand85 Glad you got it to work. To help others in the future, what did you do to solve the problem?

**Comment by mohand85** [comment]
Thank you
Yes indeed, I have a text that contains French and Arabic at the same time, so I just create a function in the view that does the tast as follows:
@if (is_arabic ($ value))
                     <td style = "; text-align: right;">
                         {{$ value}}
                     </ Td>
                     @else
                         <td style = "text-align: right; font-family: Sans-Serif; font-size: 14px;">
                             {{$ value}}
                         </ Td>
                     @endif


the is_arabic function is as follows:
  function is_arabic ($ value)
{
if (preg_match ('/ [\ x {0600} - \ x {06FF} \ x] {1,32} / u', $ value)) {
return true;
} else {
return false;
}
}
