### ISSUE TITLE
Can't use external CSS

### ISSUE THREAD

**Issue by drizki** [niklasravnsborg/laravel-pdf#59]
Hi, 
Thanks for the great package!

I need to generate multiple document and each has distinct content but share the same style. I could totally do that using inline `<style>` but it would be nice if I can manage the style in separate file. I tried:

`<link rel="stylesheet" href="mycss.css">`
`<link rel="stylesheet" href="{{public_path('css/mycss.css')}}">`
`<link rel="stylesheet" href="{{base_path('public/css/mycss.css')}}">` 

In my view file but the style would not load and I get no error whatsoever (can't inspect a pdf document, duh)

On the [mPdf documentation](https://mpdf.github.io/reference/mpdf-functions/writehtml.html), I can override the `WriteHTML($html)` CSS parse parameter to `WriteHTML($stylesheet, 2)`.
Can it be achieved using this package? If so, how can I do that?

I might missed something so please give me a pointer.

Thank you!

**Comment by niklasravnsborg** [comment]
I would advice you to use inline styles. Use a separate `.blade.php` file and include it in your pdf view to keep your files short.

e.g. style.blade.php
```html
<style>
  .your-element {
    your: css;
  }
</style>
```
