### ISSUE TITLE
Tip: for use Persian Or Arabic

### ISSUE THREAD

**Issue by saeedvir** [niklasravnsborg/laravel-pdf#64]
Dowload From 👍 

https://github.com/Gue3bara/Montserrat-Arabic

https://github.com/rastikerdar/shabnam-font

and use  this : 

	'custom_font_path' => base_path('/storage/fonts/'), // don't forget the trailing slash!
	'custom_font_data' => [
		'arabic-font' => [
			'R'  => 'arabic-font.ttf',    // regular font
			'B'  => 'arabic-font.ttf',          // optional: bold font
			'I'  => 'arabic-font.ttf',    // optional: italic font
			'BI' => 'arabic-font.ttf',           // optional: bold-italic font
			'useOTL' => 0xFF,
			'useKashida' => 75,
	   ],
		'shabnam' => [
			'R'  => 'shabnam.ttf',    // regular font
			'B'  => 'shabnam.ttf',          // optional: bold font
			'I'  => 'shabnam.ttf',    // optional: italic font
			'BI' => 'shabnam.ttf',           // optional: bold-italic font
			'useOTL' => 0xFF,
			'useKashida' => 75,
	   ],

	]

**Comment by BBEDERRAR** [comment]
but where i past the font in laravel ???

**Comment by BBEDERRAR** [comment]
but where i past the font in my project ??

**Comment by niklasravnsborg** [comment]
@saeedvir This is not an issue exactly. Feel free to open up a PR where you add your tip to the documentation though. :)

**Comment by enasellithy** [comment]
good solve
