### ISSUE TITLE
Configuration overwrite 

### ISSUE THREAD

**Issue by nayeliflores7** [niklasravnsborg/laravel-pdf#68]
Hi, I have just a couple of problems, I can't overwrite the configuration by passing it in parameters, like this way:

`$pdf = PDF::loadView('reportes.alumnos.inscripcion', $this->data, [], [
            'format'            => 'A3',
            'orientation'       => 'L',
            'title'             => 'Laravel mPDF',
            'default_font_size' => '7',
        ]);`

Neither the footer and PAGENO works for me.

Thanks a lot.

**Comment by niklasravnsborg** [comment]
Hey @nayeliflores7, changing the format is a little bit confusing in mpdf. I cleaned it up in 2.0. It should work like so: 

```php
<?php
$pdf = PDF::loadView('reportes.alumnos.inscripcion', $this->data, [], [ 'format' => 'A3-L' ]);
?>
```

To change the title and font size using the `<title>` tag and CSS `font-size` in your template. ☺️ 

Hope i could help
