### ISSUE TITLE
mPDF Error - cannot find TTF TrueType font file

### ISSUE THREAD

**Issue by DenverBYF** [niklasravnsborg/laravel-pdf#69]
I Get an error when I use it...
`mPDF Error - cannot find TTF TrueType font file - /vendor/mpdf/mpdf/ttfonts/DejaVuSansCondensed.ttf`
What can I do about it?

**Comment by niklasravnsborg** [comment]
@DenverBYF Hey sorry for the late answer. Did you use custom fonts at all?
To me it looks like the installation might be corrupt. Try to reinstall using `rm -rf vendor/ composer.lock && composer install`.

Let me know if this helps :)

**Comment by niklasravnsborg** [comment]
I suspect you figured it out.
Merry Christmas ☃️

**Comment by mohammad-salehnia** [comment]
Hi there 
I have the same problem in Laravel 6 for custom font and `rm -rf vendor/ composer.lock && composer install.` not help!
