### ISSUE TITLE
Orientation landscape doens't work

### ISSUE THREAD

**Issue by jurgentreep** [niklasravnsborg/laravel-pdf#7]
I set the orientation to landscape in my config file but the page is not rotating.
```'orientation'        => 'L'```

**Comment by niklasravnsborg** [comment]
@jurgentreep Hey! Does this help? https://github.com/niklasravnsborg/laravel-pdf/issues/5

**Comment by jurgentreep** [comment]
@niklasravnsborg I'm sorry for not looking through existing issues first. Thanks for this wrapper I had some issues with the other version.

**Comment by niklasravnsborg** [comment]
@jurgentreep No problem. It's still weird that `'orientation' => 'L'` doesn't work. I need to fix it.
