### ISSUE TITLE
Multiple CSS classes not working?

### ISSUE THREAD

**Issue by godbout** [niklasravnsborg/laravel-pdf#70]
Hi there.

I'm trying to use multiple CSS classes, but it seems that it's not being recognized (single classes work fine).

E.g.:

CSS
```
.hero.is-dark {
    background-color: #363636;
    color: whitesmoke;
}
```

HTML
```
<div class="hero is-dark">
    <h1>Trying to get some shit done</h1>
</div>
```

`.hero.is-dark` is not recognized when I generate the PDF, but works fine when I dump the normal view. If I remove `.is-dark` the class is applied (but of course my whole CSS contains a lots of those multiple classes, and therefore don't work).

Any idea what's happening?

**Comment by niklasravnsborg** [comment]
@godbout Unfortunately this is not supported by mpdf: https://mpdf.github.io/css-stylesheets/introduction.html.

To give you an alternative maybe you can try a [BEM](http://getbem.com/) style modifier class like so: `hero--is-dark` which you can use with simple css: 

```css
.hero--is-dark {
  background-color: #363636;
  color: whitesmoke;
}
```

**Comment by godbout** [comment]
@niklasravnsborg Thanks for taking the time to answer! I found at that it was a bit dumb from me to expect mpdf (or others) to be able to handle full css frameworks. I ended up doing some simple but strict CSS especially for the PDF generation.

Didn't know about BEM. Great to learn something new. Deeply appreciated!

**Comment by niklasravnsborg** [comment]
@godbout Thanks. Appreciate it :)
