### ISSUE TITLE
tempDir config not supported

### ISSUE THREAD

**Issue by josefryzi** [niklasravnsborg/laravel-pdf#73]
Hi, I am trying to set "tempDir" property config/pdf.php but this property is ignored.

Is there a way, how to set mPDF config directly?

Thanks

**Comment by Tezkerek** [comment]
I added this in #74

**Comment by niklasravnsborg** [comment]
Why would this be useful? 🤔

**Comment by Tezkerek** [comment]
The mpdf docs recommend changing the temp location.

**Comment by niklasravnsborg** [comment]
Further discussion on #74
