### ISSUE TITLE
Undefined variable: data: Issues passing data to .blade file

### ISSUE THREAD

**Issue by TomPuhakka** [niklasravnsborg/laravel-pdf#76]
I'm doing something wrong when I try to get data from the function to the .blade file.

With the error message:

> ErrorException (E_ERROR)
> Undefined variable: data (View: /home/vagrant/code/blog/resources/views/pdf/preview.blade.php)

I use the example code:
        `
    $data = [
                'foo' => 'bar'
            ];
            $pdf = PDF::loadView('pdf.preview', $data);
            return $pdf->stream('Preview.pdf');
`

preview.blade.php
`{{$data ['foo']}}`

What can I do wrong?
Thank you for your help and answers :)

**Comment by vertisan** [comment]
`$data` variable is only containing 'data'. You can access it by keys of this variable, eg.

***controller file***
```
$data = [ 'foo' => 'bar' ]; $pdf = PDF::loadView('pdf.preview', $data); return $pdf->stream('Preview.pdf');
```

***view file***
```
{{ $foo }} 

{{-- $foo will return 'bar' --}}
```

**Comment by TomPuhakka** [comment]
Thx for your help!

**Comment by gitsakil09** [comment]
You can also send the array variable using laravel's compact. Something like 
`$data = [
      'foo' => 'bar' 
]; 

$pdf = PDF::loadView('pdf.preview', compact('data')); 

return $pdf->stream('Preview.pdf');`

View file
`{{ $data->foo }}`
