### ISSUE TITLE
Page Number In Footer 

### ISSUE THREAD

**Issue by phuongphally** [niklasravnsborg/laravel-pdf#77]
Hello sir!

I can display footer by user ``  {PAGENO} ``. 

My question is i want to display page number with total number.  

example 
 - 4/1
 - 4/2
 - 4/3
 - 4/4

Thanks.

**Comment by loobooger** [comment]
Try to use:
{nb}/{PAGENO}

**Comment by phuongphally** [comment]
It worked . Thanks
