### ISSUE TITLE
Why Version 2.0 not work with Mpdf 7.0

### ISSUE THREAD

**Issue by TholthoeunChansovann** [niklasravnsborg/laravel-pdf#78]
Hi, now i try using niklasravnsborg version 2.0 but it not work for me. have any issue Thank for help me

**Comment by niklasravnsborg** [comment]
Version 2.0 works in a production environment of my company already. Please give us a more detailed description of what you are trying to do. Please send us eventual error messages you are getting.

**Comment by TholthoeunChansovann** [comment]
Thank for reply me. Before I use version 1.5 it ok but now I start using PHP version 7.2.0 it not work like before. I cannot modify it on pdf.php it not work.

**Comment by niklasravnsborg** [comment]
Send me your error messages and your current configuration files. Otherwise we won't be able t help you
