### ISSUE TITLE
Call to undefined method mPDF::loadView()

### ISSUE THREAD

**Issue by ratebz** [niklasravnsborg/laravel-pdf#8]
i'm trying to work with this package but i'm seeing this error

`Call to undefined method mPDF::loadView()` also tried any other actions and its not woking

This is my code:

`use MPDF;`
`$data = [`
`'foo' => 'bar'`
`];`
`$pdf = MPDF::loadloadHTML('web.pdf.contract', $data);`
`return $pdf->stream('document.pdf');`

in the service provider and aliases array:
`'niklasravnsborg\LaravelPdf\PdfServiceProvider',`
`'MPDF'         => 'niklasravnsborg\LaravelPdf\Facades\Pdf'`

and im using Laravel 5.0

**Comment by niklasravnsborg** [comment]
@ratebz Hey there! Maybe it's the typo in `$pdf = MPDF::loadloadHTML('web.pdf.contract', $data);`. You need to use a single `load`? Does this help?

**Comment by niklasravnsborg** [comment]
@ratebz I'll close this now due to inactivity. Let me know if you need any further help 😌
