### ISSUE TITLE
Undefined index : direction and y

### ISSUE THREAD

**Issue by saintadjie** [niklasravnsborg/laravel-pdf#80]
hai, i have got an error
if my report more than 1 page it's got error undefined index : direction
sometimes got error Undefined index: y

this is the screen shot : http://prntscr.com/hze2y0
and this one ; http://prntscr.com/hze7nj

I only use this setting
$pdf       = PDF::loadView('transaksi::pksatu/exportpdf', ['rs'=>$data], [], ['orientation' => 'L', 'format' => 'A5-L', 'default_font' => 'arial']);
return $pdf->stream("Report.".pdf");

**Comment by virusphp** [comment]
same me tooo

**Comment by saintadjie** [comment]
solve, use it without thead
