### ISSUE TITLE
custom font not working on version 2 with mpdf 7

### ISSUE THREAD

**Issue by 1razzaghi** [niklasravnsborg/laravel-pdf#81]
hi i added the custom font in the config file=> pdf.php
but it is not working
it is also working on the other project with older version laravel-pdf with mpdf 6.x

**Comment by 1razzaghi** [comment]
i fix the problem myself
the problem is in addCustomFontsConfig function on Pdf.php file in \vendor\niklasravnsborg\laravel-pdf\src\LaravelPdf\Pdf.php directory.

first bug is in the if condition  `if (!Config::has('pdf.font_path') || !Config::has('pdf.font_data'))`
there is no any config value for `pdf.font_path` and `pdf.font_data` ! so the condition return the `$mpdf_config` variable without any changes and add custom font

for solving this condition issue change the condition to
` if (!Config::has('pdf.custom_font_path') || !Config::has('pdf.custom_font_data'))`

the second bug is assigning value to $mpdf_config['fontDir'] and $mpdf_config['fontdata'] with the wrong config value that are'nt exist.
for solving this just change the value of two variable with the correct config value : 

`$mpdf_config['fontDir'] = array_merge($fontDirs, [Config::get('pdf.custom_font_path')]);
$mpdf_config['fontdata'] = array_merge($fontData, Config::get('pdf.custom_font_data'));`

**Comment by chireenjavier** [comment]
Hi 1razzaghi,
I have a similar issue. I tried to fix this with your solution, howver nothing happened for me. Where can o find the 
`$mpdf_config['fontdata'] = array_merge($fontData, Config::get('pdf.custom_font_data'));` ?

Thanks :)

**Comment by 1razzaghi** [comment]
the problem is in addCustomFontsConfig function on Pdf.php file in \vendor\niklasravnsborg\laravel-pdf\src\LaravelPdf\Pdf.php directory

**Comment by daveismyname** [comment]
hey guys did you try using `font_path` instead of `customer_font_path` ?

I've been able to add a custom font just by adding this to the config:

```
    'font_path' => public_path('fonts'),
    'font_data' => [
        'barcode_font' => [
            'R'  => 'c39hrp36dltt.ttf',    // regular font
        ]
    ]
```
