### ISSUE TITLE
New owner for this package

### ISSUE THREAD

**Issue by niklasravnsborg** [niklasravnsborg/laravel-pdf#83]
Hey there! Recently it's been hard for me to progress development on this package and give proper support. This is in part because my companies app is soon moving away from this package.

If there is anyone who would like to continue working on this repo, reach out to me! :)

**Comment by daveismyname** [comment]
Hi, thanks for this package it's really useful I've been using MPDF for years, since moving the Laravel I wanted to use a package instead.

I would be really happy to support this repo.

**Comment by niklasravnsborg** [comment]
Thanks to Dave for supporting this package from now on. 😌

**Comment by erfansahaf** [comment]
Hey Niklas, really appreciate you for working on this package, it's very useful since other libraries do not support other languages.

We are going to use this package for our company Laravel based project, so I can keep supporting it for UTF-8 character set languages such as Persian and Arabic.

**Comment by niklasravnsborg** [comment]
@erfansahaf Awesome Erfan! Appreciate it. I also added you as a collaborator to this repo 🙉
