### ISSUE TITLE
error mkdir(): File exists

### ISSUE THREAD

**Issue by birkhoff111001** [niklasravnsborg/laravel-pdf#84]
Hi, I Installed Mpdf With Composer, At First Give Me An Error That Says : " Temporary files directory "/home/dd/public_html/.../vendor/niklasravnsborg/laravel-pdf/src/config../temp/" is not writable"
I Change The Permision Of The Temp Folder At "vendor\niklasravnsborg\laravel-pdf\src\config\temp" To 0777 But It Give Me An Error Again "mkdir(): File exists"
I Read # [error mkdir()](https://github.com/mpdf/mpdf/issues/534) About This Error In Mpdf But It Doesnt Solve My Problem. Plz Help :confused:
Here Is My Codes:
In Web.php
`
use niklasravnsborg\LaravelPdf\Facades\Pdf as PDF;
`
`
Route::get('/pdf',function(){
`
`
	$pdf = PDF::loadView('welcome');
`
`
	return $pdf->stream('document.pdf');
});
`

And Welcome Is Default Welcome Laravel Blade.

**Comment by daveismyname** [comment]
Confirmed! 

If you haven't already publish the config file then change the temp path to this:

```
'tempDir'               => base_path('../temp/')
```

Please confirm this works, it worked for me. I'll then issue a new release with this change.

**Comment by birkhoff111001** [comment]
yes yes , this is work!
very thanks dave.

**Comment by Padi-dev-hoangdv** [comment]
I have same problem on server even with publish vendor `'tempDir' => base_path('../temp/')
`
