### ISSUE TITLE
Custom Font :(

### ISSUE THREAD

**Issue by birkhoff111001** [niklasravnsborg/laravel-pdf#85]
Hi Guys
I want to add custom persian font but it doesn't work.
before any thing  I have to say I check All off issues about custom fonts in this package and they doesn't solve my problem. please tell me Where is my mistake?
this is my pdf.php config file:

`
`return [ `

    'font_path' => base_path('resources/fonts/'),
    'font_data' => [
        'BYekan' => [
            'R'  => 'BYekan.ttf',    // regular font
            'useOTL' => 0xFF,    // required for complicated langs like Persian, Arabic and Chinese
            'useKashida' => 75,  // required for complicated langs like Persian, Arabic and Chinese
        ]
    ],
	'mode'                  => 'utf-8',
	'format'                => 'A4-L',
	'author'                => '',
	'subject'               => '',
	'keywords'              => '',
	'creator'               => 'Laravel Pdf',
	'display_mode'          => 'fullpage',
    'tempDir' => base_path('../temp/')
`];`
`

and i uploaded my fonts in resources/fonts.
and in the blade that converting to pdf set it to BYekan:

`
    <style>
        body {
            font-family: 'BYekan', sans-serif;
        }
    </style>
`

I try too many standard fonts that some of theme have OTL errors and some of them not , but still not working.
this is the fonts i'm using: 
[IrYekan](http://irfont.ir/fonts/%D8%AF%D8%A7%D9%86%D9%84%D9%88%D8%AF-%D9%86%D8%B3%D8%AE%D9%87-%D8%AC%D8%AF%DB%8C%D8%AF-%D9%81%D9%88%D9%86%D8%AA-%D8%A8%DB%8C-%DB%8C%DA%A9%D8%A7%D9%86-b-yekan) 

[standard persian fonts](http://bestical.rocks/f/Standardized-Persian-Fonts-By-SCICT.zip)

even i add this fonts to `vendor\mpdf\mpdf\src\Config\FontVariables.php` and add the fonts to `vendor\mpdf\mpdf\ttfonts` but it still not working. Where is my mistake?
plz help.

**Comment by jedlicka82** [comment]
Try to change BYekan to byekan in pdf.php config file. It has something to do with CSS font-family tansformations to lowercase + nospaces so "Some Random Font" should be "somerandomfont" in config. This worked for me - I have changed:
```
'font_data' => [
  'Open Sans' => [
    'R'  => 'OpenSans-Regular.ttf'
  ], 
]
```
to
```
'font_data' => [
  'opensans' => [
    'R'  => 'OpenSans-Regular.ttf'
  ], 
]
```
In my css file `font-family: 'Open Sans', Sans-serif;`

**Comment by birkhoff111001** [comment]
@jedlicka82 Thanks Alot.
Problem Solved.

Thanks dude.

**Comment by musioks** [comment]
> Try to change BYekan to byekan in pdf.php config file. It has something to do with CSS font-family transformations to lowercase + nospaces so "Some Random Font" should be "somerandomfont" in config. This worked for me - I have changed:
> 
> ```
> 'font_data' => [
>   'Open Sans' => [
>     'R'  => 'OpenSans-Regular.ttf'
>   ], 
> ]
> ```
> to
> 
> ```
> 'font_data' => [
>   'opensans' => [
>     'R'  => 'OpenSans-Regular.ttf'
>   ], 
> ]
> ```
> In my css file `font-family: 'Open Sans', Sans-serif;`

This solved my problem.

**Comment by AhmedHdeawy** [comment]
@jedlicka82 
thanks a lot, problem solved
