### ISSUE TITLE
not work with bootstrap 4

### ISSUE THREAD

**Issue by mShbieb** [niklasravnsborg/laravel-pdf#86]
"Invalid size representation "a4""

**Comment by daveismyname** [comment]
can you clarify on this?

**Comment by mShbieb** [comment]
when i run the method for export Blade to PDF, it take a long time then return this exception (Invalid size representation "a3").
I use laravel 5.5 and bootstrap 4.
and when i disable bootstrap it work

**Comment by daveismyname** [comment]
okay so b4 ships with this css rule:

```
@page{size:a3}
```

Change that to auto to stop the error being generated.

```
@page{size:a3}
```

essentially the style in bootstrap is interfering with MPDF.
