### ISSUE TITLE
Change orientation at run-time

### ISSUE THREAD

**Issue by boofman15** [niklasravnsborg/laravel-pdf#9]
Does the orientation have to be specific in the config/pdf.php file and be the same for all PDFs generated?  Or can you dynamically override the config settings when you create a PDF?

Thanks!

**Comment by niklasravnsborg** [comment]
Indeed! Try to use the CSS `@page { $size: <length>{1,2} | auto | portrait | landscape }`-attribute. You can find out more about it here: https://mpdf.github.io/paging/using-page.html

**Comment by boofman15** [comment]
Thanks for your reply.  Unfortunately, @page is not working.  I can control other styles on the PDF (font size, background-color, etc.) using @page but it does not control the pdf orientation.  Seems like the only way to control orientation is through the pdf.php config's format property.

**Comment by niklasravnsborg** [comment]
@boofman15 Okay! I reopened this. Unfortunately I don't have the time to look into it right now. If you want you can submit a PR if you find out how to fix this.

I'll definitely come back to this later...

**Comment by ferdiebergado** [comment]
Try this: 
Change line 1374 of mpdf/mpdf.php from $pfo = 'P' to $pfo = $orientation

**Comment by niklasravnsborg** [comment]
@boofman15 Looking into this again... So you want to create multiple PDFs with different page layouts, right?

**Comment by niklasravnsborg** [comment]
@boofman15 I implemented custom config in 2dc7281c1b6f520a018e9868c2ec9d815748ad5e. Does this work for you?

**Comment by boofman15** [comment]
I actually decided to go with laravel-snappy (https://github.com/barryvdh/laravel-snappy) to provide pdf functionality.  So I have not attempted to add any of these udpates.  Thanks for following up.

**Comment by niklasravnsborg** [comment]
@boofman15 Awesome. Glad you found something that works for you. 😌
