### ISSUE TITLE
Call to undefined method SetWatermarkText()

### ISSUE THREAD

**Issue by tsaini530** [niklasravnsborg/laravel-pdf#93]
After upgrade laravel  5.4 to 5.6 set watermark function  give an error:
**Call to undefined method niklasravnsborg\LaravelPdf\Pdf::SetWatermarkText();**

**Comment by niklasravnsborg** [comment]
@tsaini530 I looked into it. This isn't actually a bug. We removed the watermark support a few versions back. There is no method `SetWatermarkText` on the `Pdf` class.

See: https://github.com/niklasravnsborg/laravel-pdf/blob/master/src/LaravelPdf/Pdf.php

As far as I can remember Watermarks always caused weird problems. Thats why we removed it in version 2 of this package. You could go back to version 1 if you want.

**Comment by erfansahaf** [comment]
@tsaini530 You can set watermark image using CSS `background-image` property just like what I did:

![image](https://user-images.githubusercontent.com/12012168/41972755-0ad155a6-7a28-11e8-9dcd-14b955dd6a0a.png)

**Comment by rodjsta** [comment]
I just accessed the mpdf class to set the watermark.

![image](https://user-images.githubusercontent.com/32949856/151700635-8036950b-1381-423e-b4ad-e5da469ac137.png)
