### ISSUE TITLE
Adding Images Stored in Public/Storage Breaks Generator

### ISSUE THREAD

**Issue by mprythero** [niklasravnsborg/laravel-pdf#94]
I have an issue that doesn't seem to want to make itself easy, so I am hoping you might be able to help. 

At the moment in my controller, I prepare my PDF view as such:

```
$employeeMedCert = $employee->attachments()->where('category','Medical Examiners Certificate')->orderBy('endDate','desc')->limit(1)->get();
$path = 'temp/humanResourcesForm-'.$now.'.pdf';
$pdf = PDF::loadView('carrier.humanResources.forms.cdlSelfCertification', compact('request','employee','carrier','employeeMedCert','attach'))->save($path);
```

None of this has posed an issue, but the problem arises in the blade:

```
@foreach($employeeMedCert as $med)
<img width="auto" height="auto" src="{{storage_path($med->attachment)}}">
{{Storage::url($med->attachment)}}
@endforeach
```

Whether I try storage_path or Storage::url, and just print the return, I get the correct value to access my image publicly. For example:

My image1.jpeg file is stored as follows:

{root}/storage/app/public/employees/image1.jpeg

And using either storage_path or Storage::url gets me the following return:

{root}/public/storage(symlink)/employees/image1.jpeg

Which then I can access the image by going to:

http://192.168.1.1/storage/employees/image1.jpeg

BUT, for some reason, even though I am giving the correct relative path, the generator gets stuck and I end up having to reset my server.

For two tests, I tried just hard-coding the values in, one with the relative path of "/storage/employees/image1.jpeg" and the other "http://192.168.1.178/storage/employees/image1.jpeg" and neither worked. For one last test, I referenced an image outside of my installation and pulled from google, and it loaded without an issue.

I only think there's something a little buggy somewhere here only because the image I am trying to reference dynamically is one I have done so without a problem in multiple other views, and I used mostly the same code throughout, so I know I should be able to access the image file.

If you can help, I'd be incredibly appreciative. Best - Matt

**Comment by masoodw1** [comment]
I am also facing the same issue. hang on while i dig deeper into it.

**Comment by mprythero** [comment]
So it looks like I have found another instance of where this is broken. In a blade I convert to a pdf, I have a logo image that is hosted on our website. Recently rather than accessing it remotely at https://www.site.com/images/logo.png, I decided to make it local and switch the image source to "/images/logo.png" to reference the images folder in my public folder in the base of my project. However, upon switching it over, it proceeded to break the pdf in a similar function as described to the incident above. It just stops, and then the entirety of Laravel needs to have caches cleared and the project re-served. Have you had any other success in locating the issue's root?
Matt

**Comment by erfansahaf** [comment]
If you are trying to use an image (`<img>` tag) in your blade file, you have to keep in mind that you can not use URLs in your `img` tag because it is a PDF file actually, not a real HTML document and it cannot fetch remote images.
If your image file is located in a path like `public/images/photo.png` in your project, instead of using ` {{ assets('images/photo.png') }} ` or ` {{ url('images/photo.png') }} ` you should use ` {{ public_path('images/photo.png') }} ` to make it work.

**Comment by erfansahaf** [comment]
If you are trying to use an image (`<img>` tag) in your blade file, you have to keep in mind that you can not use URLs in your `img` tag because it is a PDF file actually, not a real HTML document and it cannot fetch remote images.
If your image file is located in a path like `public/images/photo.png` in your project, instead of using ` {{ assets('images/photo.png') }} ` or ` {{ url('images/photo.png') }} ` you should use ` {{ public_path('images/photo.png') }} ` to make it work.

**Comment by mprythero** [comment]
@erfansahaf  - does this work for stored images as well? Because at the moment I am not getting a return in image form for the following: {{public_path($driver->photoID->attachment)}} and that specific field returns a string of 'public/employees/...........jpg'

**Comment by erfansahaf** [comment]
@mprythero In my case it does.
If your project public path is different (like `public_html` or something) you have to change your image path manually.

We have launched our PDF output feature and it's working well on the production:
http://laminor.ir/artists/%D9%85%D9%87%D8%AF%DB%8C-%D8%B7%D8%A7%D9%84%D9%82%D8%A7%D9%86%DB%8C/%D9%82%D8%B1%D8%A7%D8%B1
If you want to check it, you can click on the green button at the bottom of the page.

**Comment by rorymcdaniel** [comment]
This solved the issue for me on my own project. I think adding this (using file path, not file url) to the initial readme would be really helpful. I'd be glad to do so in a pull request if you'd like.

**Comment by erfansahaf** [comment]
@rorymcdaniel That would be nice!
