### ISSUE TITLE
Compatibility with php 7.2

### ISSUE THREAD

**Issue by stealthrob** [niklasravnsborg/laravel-pdf#96]
There is a bug, with the count() function in php 7.2, ¿Are you planning to release a bugfix for php 7.2 compatibility ?

**Comment by erfansahaf** [comment]
Please be more clear about the occurred error and its message.

**Comment by niklasravnsborg** [comment]
@erfansahaf Any news on this. Did you try using this package on PHP 7.2?

**Comment by erfansahaf** [comment]
@niklasravnsborg Not yet. We are on PHP 7.1.9 right now and it's working perfectly. I will test it on PHP 7.2 in the next few days and I'll inform you all.

**Comment by niklasravnsborg** [comment]
@erfansahaf This is great. Thanks :)

**Comment by niklasravnsborg** [comment]
@erfansahaf Just looked into our production Dockerfile. We use php:7.2-fpm and the laravel-pdf works like a charm. ☺️
