### ISSUE TITLE
Undefined index: inherit

### ISSUE THREAD

**Issue by nam-co** [niklasravnsborg/laravel-pdf#97]
Hi, thanks for your work in the package, could you please help me, Im getting this Undefined index: inherit in the file /vendor/mpdf/mpdf/src/Tag/Td.php line 208 ( $c['a'] = self::ALIGN[strtolower($properties['TEXT-ALIGN'])]; )

Appreciate any help

**Comment by niklasravnsborg** [comment]
@nam-co Hey nam! Could you please provide the code you are trying to run? This could be a bug with mpdf, which this package is based on...

**Comment by nam-co** [comment]
Hi, its a laravel app, and I have  $pdf = \PDF::loadView($template, ['biz' => $biz,'client' => $client,'creating_pdf' => TRUE]);
But I got it working by just removing rel="stylesheet" from <link href="{{url('assets/css/front.css')}}"> , now the pdf is created but it doesn't include any css, is this normal? does it have to be inline?

thanks

**Comment by niklasravnsborg** [comment]
Yep I guess. You have to use the `<style>` tags. If you want to clean up you code, include a additional `.blade.php` for your styling. :)

**Comment by nam-co** [comment]
Hi Niklas, thanks for the response, I did, but I immediately get a server error:
Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.

I did it both ways, pasting the css in the file and @include('style'), they both get this error, Im using B4 just in case

**Comment by niklasravnsborg** [comment]
Please try to isolate the error. Strip out code that you don't think is related and try to reproduce it with this minimal code. Then send me your template and your usage using something like https://pastebin.com, please

**Comment by nam-co** [comment]
Hi @niklasravnsborg , I tried with half the css and it worked but strange it breaks when the css its complete
https://pastebin.com/V9VXDNie

**Comment by nam-co** [comment]
thanks for all your help

**Comment by niklasravnsborg** [comment]
@nam-co Well this is a bunch of CSS. I guess you shouldn't be using this. First thing that strikes me is the use of CSS variables. I'm pretty sure they aren't supported by mpdf.

Please isolate the error more and also send over the the template itself and the controller. One would need your code to reproduce the error.

**Comment by nam-co** [comment]
Hi @niklasravnsborg thanks for the response, I will work on it

**Comment by nam-co** [comment]
@niklasravnsborg do you know of any tool online that can parse the css and process/erase all variables? this is a regular bootstrap 4, so I think most modern css frameworks will use css variables from now on

**Comment by niklasravnsborg** [comment]
@nam-co Please, don't use a fully fledged framework in your mPDF. I often use tables for layouting. mPDF only implements a very basic version of the CSS spec. Some new features are supported but Bootstrap etc. aren't suited for mPDF.

**Comment by erfansahaf** [comment]
@nam-co In my experience, as far as your CSS gets more complicated you will be faced with more problems. Just try to keep your CSS styles as simpler as it can be.

**Comment by thallesdaniell** [comment]
I detected this and decided to extract the bootstrap for the style tag and tested it until I reached that style and removing it worked for me
```
    th {
        text-align: inherit
    }
```
