### ISSUE TITLE
Issue Displaying QRCode on PDF

### ISSUE THREAD

**Issue by LordRahl90** [niklasravnsborg/laravel-pdf#98]
I am using a QRCode generator and i have been having issue removing the xml declaration.
Please,  is there any way it can be removed? It does not show if I am displaying the HTML but it only shows when its converted to PDF.

Attached is the image of the issue i am having.
<img width="348" alt="screen shot 2018-06-27 at 2 19 48 pm" src="https://user-images.githubusercontent.com/5837848/41982335-1bca7e6e-7a23-11e8-8a93-1bd38aa984f4.png">

**Comment by erfansahaf** [comment]
@LordRahl90 First, generate your QRCode image and save it in a path (`storage` or `public`), then, use it as a simple image tag like so:
```html
<img src="{{ public_path('images/qr-codes/yourQRCodeImage.png') }}">
```
