### ISSUE TITLE
Adding Fonts

### ISSUE THREAD

**Issue by lijith** [niklasravnsborg/laravel-pdf#99]
Hi,
I am using this package for a client. And he wants to use different font for a particular file.
I tried to add using some methods explained by other, but so far none is working.

first method is tried was by modifying the vendor folder itself.
Added the roboto files to vendor>mpdf>mpdf> ttfonts
then i added font entries FontVariables.php as below
`$this->defaults = [
..
..
"roboto" => [
				    'R' => "Roboto-Regular.ttf",
				    'B' => "Roboto-Bold.ttf",
				    'I' => "Roboto-Italic.ttf",
				    'BI' => "Roboto-BoldItalic.ttf",
				]
]`
then i called the font inside html style but there is no change

2nd method i tried sending a custom config on loadview as explained in another thread
`
$mpdf_config = [
					'default_font' 		=> 'roboto',
					'custom_font_path' 	=> base_path('resources/fonts/'),
					'orientation'		=> 'L',
					'custom_font_data' 	=> [
						'roboto' => [
						    'R' => "Roboto-Regular.ttf",
						    'B' => "Roboto-Bold.ttf",
						    'I' => "Roboto-Italic.ttf",
						    'BI' => "Roboto-BoldItalic.ttf",
						]
					]
				];
$pdf = \PDF::loadView('pdf/service_invoice',['service' => $service],[],$mpdf_config);
`
and put the fonts inside resources/fonts but still not working
i put the custom config inside config>pdf file, still no success

what am i doing wrong?

**Comment by erfansahaf** [comment]
Hey @lijith ,
[Here](https://github.com/niklasravnsborg/laravel-pdf#custom-fonts) is the instruction for using the custom fonts. Read the documentation first, then open an issue if you couldn't find what you are looking for.
